{
    ["WT"] = {
        ["announcement"] = {
            ["enable"] = false,
            ["keystone"] = {
                ["enable"] = false,
            },
            ["quest"] = {
                ["channel"] = {
                    ["raid"] = "NONE",
                },
            },
            ["resetInstance"] = {
                ["enable"] = false,
            },
            ["utility"] = {
                ["enable"] = false,
            },
        },
        ["combat"] = {
            ["combatAlert"] = {
                ["animation"] = false,
                ["enable"] = false,
                ["enterSound"] = {
                    ["sound"] = "BBQ Ass",
                },
                ["text"] = false,
            },
            ["raidMarkers"] = {
                ["enable"] = false,
            },
        },
        ["item"] = {
            ["extraItemsBar"] = {
                ["bar1"] = {
                    ["backdrop"] = false,
                    ["bindFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["countFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["enable"] = false,
                },
                ["bar2"] = {
                    ["backdrop"] = false,
                    ["bindFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["countFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["bar3"] = {
                    ["backdrop"] = false,
                    ["bindFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["countFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["bar4"] = {
                    ["backdrop"] = false,
                    ["backdropSpacing"] = 1,
                    ["bindFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["buttonHeight"] = 36,
                    ["buttonWidth"] = 36,
                    ["countFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                        ["size"] = 14,
                        ["xOffset"] = -7,
                        ["yOffset"] = -5,
                    },
                    ["enable"] = true,
                    ["include"] = "POTIONTWW,POTIONMN,UTILITY,CUSTOM",
                    ["qualityTier"] = {
                        ["size"] = 20,
                    },
                    ["spacing"] = 1,
                },
                ["bar5"] = {
                    ["bindFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                    ["countFont"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["enable"] = false,
            },
            ["inspect"] = {
                ["enable"] = false,
                ["levelText"] = {
                    ["name"] = "ITCAvantGardeGothicDemi",
                },
            },
            ["itemLevel"] = {
                ["flyout"] = {
                    ["font"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["scrappingMachine"] = {
                    ["font"] = {
                        ["name"] = "ITCAvantGardeGothicDemi",
                    },
                },
            },
            ["trade"] = {
                ["thanksButton"] = false,
            },
        },
        ["maps"] = {
            ["eventTracker"] = {
                ["enable"] = false,
                ["style"] = {
                    ["backdrop"] = false,
                },
            },
        },
        ["misc"] = {
            ["disableTalkingHead"] = true,
            ["gameBar"] = {
                ["enable"] = false,
            },
        },
        ["quest"] = {
            ["switchButtons"] = {
                ["announcement"] = false,
                ["turnIn"] = false,
            },
            ["turnIn"] = {
                ["getBestReward"] = true,
            },
        },
        ["skins"] = {
            ["vignetting"] = {
                ["enable"] = false,
            },
        },
        ["social"] = {
            ["chatBar"] = {
                ["buttonHeight"] = 10,
                ["buttonWidth"] = 36,
                ["enable"] = false,
                ["spacing"] = 4,
            },
        },
        ["tooltips"] = {
            ["elvUITweaks"] = {
                ["betterMythicPlusInfo"] = {
                    ["icon"] = {
                        ["enable"] = false,
                    },
                },
                ["raceIcon"] = {
                    ["enable"] = false,
                },
            },
            ["groupInfo"] = {
                ["enable"] = false,
            },
            ["keystone"] = {
                ["icon"] = {
                    ["height"] = 16,
                },
            },
        },
        ["unitFrames"] = {
            ["absorb"] = {
                ["blizzardOverAbsorbGlow"] = false,
                ["enable"] = true,
                ["texture"] = {
                    ["blizzardStyle"] = false,
                },
            },
        },
    },
    ["actionbar"] = {
        ["bar1"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = -1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "ITCAvantGardeGothicDemi",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["visibility"] = "[petbattle] hide; [vehicleui][overridebar][possessbar] show; hide",
        },
        ["bar10"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar13"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar14"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar15"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar2"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = -1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFontOutline"] = "OUTLINE",
            ["visibility"] = "hide",
        },
        ["bar3"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = -1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFontOutline"] = "OUTLINE",
            ["visibility"] = "hide",
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 40,
            ["buttonSpacing"] = -1,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFontOutline"] = "OUTLINE",
            ["point"] = "BOTTOMLEFT",
            ["visibility"] = "hide",
        },
        ["bar5"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = -1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFontOutline"] = "OUTLINE",
            ["visibility"] = "hide",
        },
        ["bar6"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["buttons"] = 6,
            ["buttonsPerRow"] = 1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFontOutline"] = "OUTLINE",
            ["professionQuality"] = {
                ["scale"] = 0.4,
                ["xOffset"] = 23,
                ["yOffset"] = -22,
            },
            ["visibility"] = "",
        },
        ["bar7"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar8"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["bar9"] = {
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["macroFontOutline"] = "OUTLINE",
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 33,
            ["buttonSpacing"] = 0,
            ["buttons"] = 8,
            ["buttonsPerRow"] = 4,
            ["countFontOutline"] = "OUTLINE",
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["extraActionButton"] = {
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["stanceBar"] = {
            ["enabled"] = false,
            ["hotkeyFontOutline"] = "OUTLINE",
        },
        ["vehicleExitButton"] = {
            ["hotkeyFontOutline"] = "OUTLINE",
            ["size"] = 41,
        },
        ["zoneActionButton"] = {
            ["clean"] = true,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["countXOffset"] = -12,
            ["countYOffset"] = 28,
            ["horizontalSpacing"] = 3,
            ["size"] = 36,
            ["wrapAfter"] = 10,
        },
        ["debuffs"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["horizontalSpacing"] = 3,
            ["size"] = 40,
            ["wrapAfter"] = 10,
        },
    },
    ["bags"] = {
        ["autoToggle"] = {
            ["trade"] = true,
        },
        ["bagSize"] = 40,
        ["bagWidth"] = 790,
        ["bankSize"] = 40,
        ["bankWidth"] = 500,
        ["clearSearchOnClose"] = true,
        ["countFont"] = "ITCAvantGardeGothicDemi",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 12,
        ["itemInfoFont"] = "ITCAvantGardeGothicDemi",
        ["itemInfoFontOutline"] = "OUTLINE",
        ["itemInfoFontSize"] = 14,
        ["itemLevelCustomColorEnable"] = true,
        ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 12,
        ["scrapIcon"] = true,
        ["split"] = {
            ["bag1"] = true,
            ["bag2"] = true,
            ["bag3"] = true,
            ["bag4"] = true,
            ["bagSpacing"] = 7,
        },
        ["transparent"] = true,
        ["vendorGrays"] = {
            ["enable"] = true,
        },
        ["warbandSize"] = 40,
    },
    ["chat"] = {
        ["copyChatLines"] = true,
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 12,
        ["panelBackdrop"] = "LEFT",
        ["panelHeight"] = 218,
        ["panelWidth"] = 500,
        ["tabFont"] = "ITCAvantGardeGothicDemi",
        ["tabFontOutline"] = "OUTLINE",
        ["tabSelectorColor"] = {
            ["b"] = 0.82,
            ["g"] = 0.51,
            ["r"] = 0.09,
        },
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["actionbar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["aurabars"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["auras"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontSize"] = 14,
            ["offsetY"] = 0,
            ["threshold"] = 3599,
        },
        ["bags"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["bossbutton"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["global"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["nameplates"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontSize"] = 14,
        },
        ["totemtracker"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["unitframe"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["threshold"] = 3599,
        },
        ["zonebutton"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["threshold"] = 3599,
        },
    },
    ["databars"] = {
        ["azerite"] = {
            ["enable"] = false,
            ["fontOutline"] = "OUTLINE",
        },
        ["experience"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontOutline"] = "OUTLINE",
            ["height"] = 15,
            ["showLevel"] = true,
            ["showQuestXP"] = false,
            ["textFormat"] = "PERCENT",
            ["width"] = 500,
        },
        ["honor"] = {
            ["enable"] = false,
            ["fontOutline"] = "OUTLINE",
        },
        ["reputation"] = {
            ["fontOutline"] = "OUTLINE",
        },
        ["threat"] = {
            ["enable"] = false,
            ["fontOutline"] = "OUTLINE",
            ["width"] = 200,
        },
    },
    ["datatexts"] = {
        ["battlePanel"] = {
            ["LeftChatDataPanel"] = {
                [2] = "PvP: Honor Gained",
                [3] = "PvP: Damage Done",
            },
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["panels"] = {
            ["LeftChatDataPanel"] = {
                [3] = "System",
            },
            ["MinimapPanel"] = {
                [1] = "Time",
            },
            ["RightChatDataPanel"] = {
                ["enable"] = false,
            },
        },
    },
    ["general"] = {
        ["addonCompartment"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontOutline"] = "OUTLINE",
            ["hide"] = true,
        },
        ["afk"] = false,
        ["altPowerBar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["height"] = 12,
            ["statusBar"] = "Melli",
        },
        ["autoRepair"] = "PLAYER",
        ["autoTrackReputation"] = true,
        ["backdropcolor"] = {
            ["b"] = 0.11764706671238,
            ["g"] = 0.11764706671238,
            ["r"] = 0.11764706671238,
        },
        ["backdropfadecolor"] = {
            ["b"] = 0.054,
            ["g"] = 0.054,
            ["r"] = 0.054,
        },
        ["bonusObjectivePosition"] = "AUTO",
        ["bottomPanel"] = false,
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fonts"] = {
            ["cooldown"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 18,
            },
            ["errortext"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 16,
            },
            ["mailbody"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["objective"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 12,
            },
            ["pvpsubzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["pvpzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["questsmall"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 12,
            },
            ["questtext"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
            },
            ["questtitle"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 16,
            },
            ["talkingtext"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 14,
            },
            ["talkingtitle"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "OUTLINE",
                ["size"] = 16,
            },
            ["worldsubzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["worldzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
            },
        },
        ["gameMenuScale"] = 0.86,
        ["guildBank"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
            ["itemLevelFontOutline"] = "OUTLINE",
        },
        ["itemLevel"] = {
            ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
            ["totalLevelFont"] = "ITCAvantGardeGothicDemi",
        },
        ["lootRoll"] = {
            ["nameFont"] = "ITCAvantGardeGothicDemi",
        },
        ["minimap"] = {
            ["icons"] = {
                ["difficulty"] = {
                    ["xOffset"] = 0,
                },
                ["mail"] = {
                    ["scale"] = 1.1,
                    ["texture"] = "Mail1",
                    ["xOffset"] = -3,
                    ["yOffset"] = 2,
                },
            },
            ["locationFont"] = "ITCAvantGardeGothicDemi",
            ["size"] = 224,
        },
        ["objectiveFrameHeight"] = 400,
        ["privateAuras"] = {
            ["borderScale"] = 1,
            ["countdownNumbers"] = true,
            ["icon"] = {
                ["amount"] = 3,
                ["offset"] = 0,
                ["size"] = 50,
            },
        },
        ["queueStatus"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["resurrectSound"] = true,
        ["talkingHeadFrameScale"] = 1,
        ["totems"] = {
            ["size"] = 36,
            ["sortDirection"] = "DESCENDING",
            ["spacing"] = 1,
        },
    },
    ["movers"] = {
        ["AdditionalPowerMover"] = "BOTTOM,UIParent,BOTTOM,0,202",
        ["AddonCompartmentMover"] = "RIGHT,ElvUI_MinimapHolder,RIGHT,-5,10",
        ["AlertFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-580,-541",
        ["AltPowerBarMover"] = "BOTTOM,UIParent,BOTTOM,0,214",
        ["ArenaHeaderMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-510,-237",
        ["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-246",
        ["BNETMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-328",
        ["BelowMinimapContainerMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-502,210",
        ["BossBannerMover"] = "TOP,UIParent,TOP,0,-227",
        ["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,141",
        ["BossHeaderMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-400,-368",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-237,-8",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-237,-208",
        ["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,2",
        ["ElvAB_10"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-320,277",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,40",
        ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,78",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,116",
        ["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,154",
        ["ElvAB_6"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,502,2",
        ["ElvAB_7"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-322,368",
        ["ElvAB_8"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-322,338",
        ["ElvAB_9"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-319,307",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-388",
        ["ElvUF_FocusCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,567",
        ["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,503,292",
        ["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,600,400",
        ["ElvUF_PetCastbarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,587,246",
        ["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,601,219",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,1,347",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-315,291",
        ["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,244",
        ["ElvUF_Raid2Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,244",
        ["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,244",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-323",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,315,277",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,315,291",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-503,291",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-2,378",
        ["ElvUIBankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,504,348",
        ["EventToastMover"] = "TOP,UIParent,TOP,0,-205",
        ["ExperienceBarMover"] = "TOP,UIParent,TOP,0,-4",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-2",
        ["HonorBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-245",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,2",
        ["LootFrameMover"] = "TOP,UIParent,TOP,280,-460",
        ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-486",
        ["MicrobarMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-4",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-8,-8",
        ["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325",
        ["PetAB"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,601,155",
        ["PowerBarContainerMover"] = "TOP,ElvUIParent,TOP,0,-70",
        ["PrivateAurasMover"] = "BOTTOM,UIParent,BOTTOM,-205,499",
        ["PrivateRaidWarningMover"] = "TOP,RaidBossEmoteFrame,TOP,0,0",
        ["QueueStatusMover"] = "BOTTOMRIGHT,ElvUI_MinimapHolder,BOTTOMRIGHT,-5,25",
        ["ReputationBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-244",
        ["RightChatMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-482",
        ["ShiftAB"] = "BOTTOM,UIParent,BOTTOM,-343,4",
        ["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
        ["TargetPowerBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-639,289",
        ["ThreatBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-246",
        ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-2,350",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-30",
        ["TorghastChoiceToggle"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-2",
        ["TotemTrackerMover"] = "BOTTOM,ElvUIParent,BOTTOM,142,357",
        ["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-166",
        ["VehicleLeaveButton"] = "BOTTOM,UIParent,BOTTOM,-200,228",
        ["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4",
        ["WTChatBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,277",
        ["WTCustomEmoteFrameMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-273",
        ["WTMinimapButtonBarAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-9,-255",
        ["WTRaidMarkersBarAnchor"] = "BOTTOM,UIParent,BOTTOM,-125,414",
        ["WTSwitchButtonBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-104,-305",
        ["WTUIErrorsFrameMover"] = "TOP,UIParent,TOP,0,-142",
        ["ZoneAbility"] = "BOTTOM,UIParent,BOTTOM,0,4",
    },
    ["nameplates"] = {
        ["colors"] = {
            ["castNoInterruptColor"] = {
                ["a"] = 1,
            },
            ["selection"] = {
                [0] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                [2] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
                [3] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
            },
            ["threat"] = {
                ["badColor"] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                ["goodColor"] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
                ["goodTransition"] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
            },
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["units"] = {
            ["ENEMY_NPC"] = {
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
            },
            ["ENEMY_PLAYER"] = {
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
                ["portrait"] = {
                    ["classicon"] = false,
                    ["enable"] = true,
                    ["position"] = "LEFT",
                    ["xOffset"] = 0,
                    ["yOffset"] = 0,
                },
            },
        },
    },
    ["tooltip"] = {
        ["anchorToBags"] = "DISABLED",
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["headerFont"] = "ITCAvantGardeGothicDemi",
        ["headerFontOutline"] = "OUTLINE",
        ["headerFontSize"] = 12,
        ["healthBar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontOutline"] = "OUTLINE",
            ["height"] = 8,
        },
        ["itemCount"] = {
            ["bank"] = true,
            ["stack"] = true,
        },
        ["visibility"] = {
            ["combatOverride"] = "ALT",
        },
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["aurabar_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["castClassColor"] = true,
            ["castColor"] = {
                ["a"] = 1,
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["castbar_backdrop"] = {
                ["b"] = 0.11764706671238,
                ["g"] = 0.11764706671238,
                ["r"] = 0.11764706671238,
            },
            ["classpower_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["colorhealthbyvalue"] = false,
            ["customcastbarbackdrop"] = true,
            ["customclasspowerbackdrop"] = true,
            ["customhealthbackdrop"] = true,
            ["custompowerbackdrop"] = true,
            ["disconnected"] = {
                ["b"] = 0.31764706969261,
                ["g"] = 0.31764706969261,
                ["r"] = 0.31764706969261,
            },
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["enable"] = false,
                },
            },
            ["healPrediction"] = {
                ["absorbs"] = {
                    ["a"] = 0.5,
                    ["b"] = 1,
                    ["g"] = 0.83137261867523,
                    ["r"] = 0.05882353335619,
                },
                ["healAbsorbs"] = {
                    ["a"] = 0.69999998807907,
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                ["maxOverflow"] = 0.01,
                ["others"] = {
                    ["a"] = 0,
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
                ["overabsorbs"] = {
                    ["a"] = 0.5,
                    ["b"] = 1,
                    ["g"] = 0.83137261867523,
                    ["r"] = 0.05882353335619,
                },
                ["overhealabsorbs"] = {
                    ["a"] = 0.69999998807907,
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                ["personal"] = {
                    ["a"] = 0,
                    ["b"] = 0.50980395078659,
                    ["g"] = 0.78431379795074,
                },
            },
            ["health"] = {
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["health_backdrop"] = {
                ["b"] = 0.26666668057442,
                ["g"] = 0.26666668057442,
                ["r"] = 0.26666668057442,
            },
            ["health_backdrop_dead"] = {
                ["b"] = 0.26666668057442,
                ["g"] = 0.26666668057442,
                ["r"] = 0.26666668057442,
            },
            ["healthclass"] = true,
            ["power_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["reaction"] = {
                [1] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                [2] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                [4] = {
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.78431379795074,
                },
                [5] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
                [6] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
                [7] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
            },
            ["useDeadBackdrop"] = true,
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 16,
        ["statusbar"] = "Melli",
        ["units"] = {
            ["arena"] = {
                ["auras"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["enable"] = true,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraBigDefensivePlayer"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["perrow"] = 3,
                    ["sizeOverride"] = 36,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraBigDefensive"] = false,
                    ["isAuraExternalDefensive"] = false,
                    ["isAuraExternalDefensivePlayer"] = false,
                    ["sizeOverride"] = 29,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = 14,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["height"] = 16,
                    ["positionsGroup"] = {
                        ["xOffset"] = 30,
                        ["yOffset"] = -17,
                    },
                    ["width"] = 191,
                },
                ["customTexts"] = {
                    ["ArenaName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[name:abbrev:long]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 29,
                    },
                    ["HP"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 5,
                        ["yOffset"] = -12,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = -12,
                    },
                },
                ["debuffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["sizeOverride"] = 29,
                    ["spacing"] = 0,
                },
                ["growthDirection"] = "UP",
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 0,
                    ["yOffset"] = -23,
                },
                ["height"] = 60,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 9,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -23,
                },
                ["pvpTrinket"] = {
                    ["size"] = 60,
                    ["xOffset"] = 0,
                },
                ["spacing"] = 30,
                ["width"] = 250,
            },
            ["assist"] = {
                ["enable"] = false,
            },
            ["boss"] = {
                ["auras"] = {
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 14,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = false,
                    ["isAuraImportantPlayer"] = false,
                    ["isAuraRaidPlayerDispellable"] = false,
                    ["maxDuration"] = 300,
                    ["priority"] = "Blacklist,Whitelist,Dispellable,TurtleBuffs",
                    ["sizeOverride"] = 39,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["castbar"] = {
                    ["customColor"] = {
                        ["color"] = {
                            ["b"] = 1,
                            ["g"] = 0.50980395078659,
                            ["r"] = 0,
                        },
                        ["colorBackdrop"] = {
                            ["b"] = 0.05882353335619,
                            ["g"] = 0.05882353335619,
                            ["r"] = 0.05882353335619,
                        },
                        ["colorInterrupted"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.78431379795074,
                            ["r"] = 1,
                        },
                        ["colorNoInterrupt"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.23529413342476,
                            ["r"] = 0.78431379795074,
                        },
                        ["enable"] = true,
                        ["useCustomBackdrop"] = true,
                    },
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 10,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 10,
                    },
                    ["displayTargetClass"] = false,
                    ["height"] = 14,
                    ["positionsGroup"] = {
                        ["yOffset"] = 2,
                    },
                    ["smoothbars"] = true,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 202,
                },
                ["customTexts"] = {
                    ["BossName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 20,
                    },
                    ["HP"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 3,
                        ["yOffset"] = -9,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = -3,
                        ["yOffset"] = 11,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 14,
                    ["desaturate"] = false,
                    ["isAuraCrowdControl"] = true,
                    ["maxDuration"] = 300,
                    ["perrow"] = 5,
                    ["sizeOverride"] = 39,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["growthDirection"] = "UP",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 0,
                    ["yOffset"] = -23,
                },
                ["height"] = 40,
                ["infoPanel"] = {
                    ["height"] = 17,
                },
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 9,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -23,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "TOPLEFT",
                },
                ["spacing"] = 22,
                ["width"] = 200,
            },
            ["focus"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["detachedWidth"] = 270,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                    ["maxBars"] = 6,
                },
                ["auras"] = {
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                },
                ["castbar"] = {
                    ["customColor"] = {
                        ["color"] = {
                            ["b"] = 1,
                            ["g"] = 0.50980395078659,
                            ["r"] = 0,
                        },
                        ["colorBackdrop"] = {
                            ["b"] = 0.12156863510609,
                            ["g"] = 0.12156863510609,
                            ["r"] = 0.12156863510609,
                        },
                        ["colorInterrupted"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.78431379795074,
                            ["r"] = 1,
                        },
                        ["enable"] = true,
                        ["useCustomBackdrop"] = true,
                    },
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 13,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 13,
                    },
                    ["height"] = 25,
                    ["iconSize"] = 50,
                    ["insideInfoPanel"] = false,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 320,
                },
                ["customTexts"] = {
                    ["FocusName"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 14,
                        ["text_format"] = "[name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 18,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "BUFFS",
                    ["enable"] = false,
                    ["growthX"] = "RIGHT",
                    ["isAuraBigDefensive"] = false,
                    ["isAuraExternalDefensive"] = false,
                    ["isAuraPlayer"] = false,
                    ["isAuraRaid"] = false,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                },
                ["disableMouseoverGlow"] = true,
                ["disableTargetGlow"] = true,
                ["healPrediction"] = {
                    ["enable"] = false,
                },
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["xOffset"] = 2,
                },
                ["height"] = 20,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 21,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["text_format"] = "||cFF007ACC[perpp<%]||r",
                    ["xOffset"] = -2,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["size"] = 20,
                    ["xOffset"] = 41,
                    ["yOffset"] = -9,
                },
                ["width"] = 97,
            },
            ["party"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "LEFT",
                    ["isAuraCancelablePlayer"] = true,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 22,
                    ["spacing"] = 0,
                    ["xOffset"] = -41,
                },
                ["buffIndicator"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["size"] = 16,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countYOffset"] = 1,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["isAuraRaidInCombatPlayer"] = false,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 31,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["useBlocklist"] = true,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["GroupName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:abbrev:short]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 36,
                    },
                    ["Status"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 16,
                        ["text_format"] = "[dead][offline]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthY"] = "DOWN",
                    ["isAuraCancelable"] = true,
                    ["isAuraCancelablePlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["notAuraCancelable"] = true,
                    ["notAuraCancelablePlayer"] = true,
                    ["numrows"] = 2,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 35,
                    ["spacing"] = 0,
                    ["yOffset"] = 2,
                },
                ["groupBy"] = "ROLE",
                ["growthDirection"] = "DOWN_LEFT",
                ["healPrediction"] = {
                    ["absorbStyle"] = "REVERSED",
                    ["anchorPoint"] = "CENTER",
                    ["enable"] = true,
                },
                ["health"] = {
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 71,
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["text_format"] = "",
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                        ["offsetY"] = 0,
                        ["point"] = "CENTER",
                    },
                    ["icon"] = {
                        ["offset"] = 0,
                        ["point"] = "RIGHT",
                        ["size"] = 30,
                    },
                    ["parent"] = {
                        ["offsetY"] = 37,
                        ["point"] = "BOTTOMLEFT",
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = 7,
                },
                ["rdebuffs"] = {
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 10,
                },
                ["roleIcon"] = {
                    ["position"] = "TOPLEFT",
                    ["size"] = 13,
                    ["xOffset"] = 0,
                    ["yOffset"] = -4,
                },
                ["verticalSpacing"] = 7,
                ["width"] = 135,
            },
            ["pet"] = {
                ["castbar"] = {
                    ["enable"] = false,
                    ["iconSize"] = 32,
                    ["width"] = 132,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["enable"] = true,
                },
                ["disableTargetGlow"] = false,
                ["height"] = 25,
                ["infoPanel"] = {
                    ["height"] = 14,
                },
                ["name"] = {
                    ["text_format"] = "",
                },
                ["power"] = {
                    ["enable"] = false,
                },
                ["width"] = 132,
            },
            ["player"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["RestIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["auras"] = {
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["buffIndicator"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                },
                ["buffs"] = {
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraBigDefensivePlayer"] = true,
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["useBlocklist"] = true,
                },
                ["castbar"] = {
                    ["customColor"] = {
                        ["color"] = {
                            ["b"] = 1,
                            ["g"] = 0.50980395078659,
                            ["r"] = 0,
                        },
                        ["colorBackdrop"] = {
                            ["a"] = 0.89999997615814,
                            ["b"] = 0.10980392992496,
                            ["g"] = 0.10980392992496,
                            ["r"] = 0.10980392992496,
                        },
                        ["colorInterrupted"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.78431379795074,
                            ["r"] = 1,
                        },
                        ["colorNoInterrupt"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.23529413342476,
                            ["r"] = 0.78431379795074,
                        },
                        ["enable"] = true,
                        ["transparent"] = true,
                        ["useCustomBackdrop"] = true,
                    },
                    ["customTextFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["height"] = 9,
                    ["hideName"] = true,
                    ["hideTime"] = true,
                    ["icon"] = false,
                    ["insideInfoPanel"] = false,
                    ["strataAndLevel"] = {
                        ["frameLevel"] = 17,
                        ["frameStrata"] = "MEDIUM",
                        ["useCustomLevel"] = true,
                        ["useCustomStrata"] = true,
                    },
                    ["width"] = 322,
                },
                ["classAdditional"] = {
                    ["width"] = 230,
                },
                ["classbar"] = {
                    ["enable"] = false,
                    ["height"] = 14,
                },
                ["customTexts"] = {
                    ["Absorbs"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[absorbs-autohide]",
                        ["xOffset"] = -2,
                        ["yOffset"] = 0,
                    },
                    ["HP"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[perhp<%] I [health:current:shortvalue]",
                        ["xOffset"] = -2,
                        ["yOffset"] = -20,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraCancelable"] = true,
                    ["isAuraCancelablePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["isAuraRaidPlayerDispellable"] = true,
                    ["notAuraCancelable"] = true,
                    ["notAuraCancelablePlayer"] = true,
                    ["perrow"] = 3,
                    ["sizeOverride"] = 50,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 2,
                    ["useBlocklist"] = true,
                    ["xOffset"] = -51,
                    ["yOffset"] = 110,
                },
                ["disableMouseoverGlow"] = true,
                ["healPrediction"] = {
                    ["absorbStyle"] = "REVERSED",
                },
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["position"] = "RIGHT",
                    ["text_format"] = "",
                },
                ["height"] = 41,
                ["partyIndicator"] = {
                    ["enable"] = false,
                },
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["position"] = "LEFT",
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["offsetY"] = 0,
                        ["point"] = "CENTER",
                    },
                    ["enable"] = true,
                    ["icon"] = {
                        ["amount"] = 3,
                        ["offset"] = 2,
                        ["point"] = "RIGHT",
                        ["size"] = 50,
                    },
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
            },
            ["raid1"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "LEFT",
                    ["perrow"] = 2,
                    ["sizeOverride"] = 22,
                    ["spacing"] = 0,
                },
                ["buffIndicator"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["profileSpecific"] = true,
                    ["size"] = 16,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countYOffset"] = 1,
                    ["growthX"] = "LEFT",
                    ["isAuraRaidInCombatPlayer"] = false,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 24,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:veryshort]",
                        ["xOffset"] = 12,
                        ["yOffset"] = 25,
                    },
                    ["Status"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 16,
                        ["text_format"] = "[dead][offline]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["enable"] = true,
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 28,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 6,
                ["growthDirection"] = "RIGHT_UP",
                ["healPrediction"] = {
                    ["absorbStyle"] = "REVERSED",
                    ["anchorPoint"] = "CENTER",
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 51,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["numGroups"] = 4,
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                        ["offsetY"] = 0,
                        ["point"] = "CENTER",
                    },
                    ["icon"] = {
                        ["offset"] = 0,
                        ["point"] = "RIGHT",
                        ["size"] = 30,
                    },
                    ["parent"] = {
                        ["offsetY"] = 30,
                        ["point"] = "BOTTOMLEFT",
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = 2,
                },
                ["rdebuffs"] = {
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["position"] = "TOPLEFT",
                    ["size"] = 13,
                    ["xOffset"] = 0,
                    ["yOffset"] = -4,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["raid2"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "LEFT",
                    ["perrow"] = 2,
                    ["sizeOverride"] = 22,
                    ["spacing"] = 0,
                },
                ["buffIndicator"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["profileSpecific"] = true,
                    ["size"] = 16,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countYOffset"] = 1,
                    ["growthX"] = "LEFT",
                    ["isAuraRaidInCombatPlayer"] = false,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 24,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:veryshort]",
                        ["xOffset"] = 12,
                        ["yOffset"] = 25,
                    },
                    ["Status"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 16,
                        ["text_format"] = "[dead][offline]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["enable"] = true,
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 28,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 6,
                ["growthDirection"] = "RIGHT_UP",
                ["healPrediction"] = {
                    ["absorbStyle"] = "REVERSED",
                    ["anchorPoint"] = "CENTER",
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 51,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["numGroups"] = 6,
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                        ["offsetY"] = 0,
                        ["point"] = "CENTER",
                    },
                    ["icon"] = {
                        ["offset"] = 0,
                        ["point"] = "RIGHT",
                        ["size"] = 30,
                    },
                    ["parent"] = {
                        ["offsetY"] = 30,
                        ["point"] = "BOTTOMLEFT",
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = 2,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["enable"] = true,
                    ["position"] = "TOPLEFT",
                    ["size"] = 13,
                    ["xOffset"] = 0,
                    ["yOffset"] = -4,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["raid3"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "LEFT",
                    ["perrow"] = 2,
                    ["sizeOverride"] = 22,
                    ["spacing"] = 0,
                },
                ["buffIndicator"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["profileSpecific"] = true,
                    ["size"] = 16,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countYOffset"] = 1,
                    ["growthX"] = "LEFT",
                    ["isAuraRaidInCombatPlayer"] = false,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 24,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:veryshort]",
                        ["xOffset"] = 12,
                        ["yOffset"] = 25,
                    },
                    ["Status"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 16,
                        ["text_format"] = "[dead][offline]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["enable"] = true,
                    ["isAuraPermanent"] = true,
                    ["isAuraPermanentPlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 28,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 6,
                ["growthDirection"] = "RIGHT_UP",
                ["healPrediction"] = {
                    ["absorbStyle"] = "REVERSED",
                    ["anchorPoint"] = "CENTER",
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 51,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                        ["offsetY"] = 0,
                        ["point"] = "CENTER",
                    },
                    ["icon"] = {
                        ["offset"] = 0,
                        ["point"] = "RIGHT",
                        ["size"] = 30,
                    },
                    ["parent"] = {
                        ["offsetY"] = 30,
                        ["point"] = "BOTTOMLEFT",
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = 2,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["enable"] = true,
                    ["position"] = "TOPLEFT",
                    ["size"] = 13,
                    ["xOffset"] = 0,
                    ["yOffset"] = -4,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["tank"] = {
                ["enable"] = false,
            },
            ["target"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                },
                ["auras"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["enable"] = false,
                    ["filter"] = "HELPFUL",
                    ["isAuraCrowdControl"] = false,
                    ["isAuraCrowdControlPlayer"] = false,
                    ["perrow"] = 8,
                    ["priority"] = "",
                    ["sizeOverride"] = 0,
                    ["xOffset"] = 0,
                },
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraBigDefensive"] = true,
                    ["isAuraBigDefensivePlayer"] = true,
                    ["isAuraCancelable"] = true,
                    ["isAuraCancelablePlayer"] = true,
                    ["isAuraCrowdControl"] = true,
                    ["isAuraCrowdControlPlayer"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraPlayer"] = true,
                    ["isAuraRaid"] = true,
                    ["isAuraRaidInCombat"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["isAuraRaidPlayerDispellable"] = true,
                    ["notAuraCancelable"] = true,
                    ["notAuraCancelablePlayer"] = true,
                    ["perrow"] = 3,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                    ["sizeOverride"] = 32,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["castbar"] = {
                    ["customColor"] = {
                        ["color"] = {
                            ["b"] = 1,
                            ["g"] = 0.50980395078659,
                            ["r"] = 0,
                        },
                        ["colorBackdrop"] = {
                            ["b"] = 0.11764706671238,
                            ["g"] = 0.11764706671238,
                            ["r"] = 0.11764706671238,
                        },
                        ["colorInterrupted"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.78431379795074,
                            ["r"] = 1,
                        },
                        ["colorNoInterrupt"] = {
                            ["b"] = 0.23529413342476,
                            ["g"] = 0.23529413342476,
                            ["r"] = 0.78431379795074,
                        },
                        ["enable"] = true,
                        ["useCustomBackdrop"] = true,
                    },
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["height"] = 16,
                    ["icon"] = false,
                    ["insideInfoPanel"] = false,
                    ["strataAndLevel"] = {
                        ["frameLevel"] = 2,
                        ["useCustomLevel"] = true,
                    },
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 271,
                    ["yOffsetText"] = -8,
                    ["yOffsetTime"] = -8,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 2,
                        ["yOffset"] = -20,
                    },
                    ["Range"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[range]",
                        ["xOffset"] = 3,
                        ["yOffset"] = 0,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = 35,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "RIGHT",
                    ["isAuraBigDefensivePlayer"] = true,
                    ["isAuraCancelablePlayer"] = true,
                    ["isAuraCrowdControlPlayer"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraRaidInCombatPlayer"] = true,
                    ["isAuraRaidPlayer"] = true,
                    ["isAuraRaidPlayerDispellable"] = true,
                    ["maxDuration"] = 0,
                    ["notAuraCancelablePlayer"] = true,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                    ["sizeOverride"] = 32,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["disableMouseoverGlow"] = true,
                ["healPrediction"] = {
                    ["enable"] = false,
                },
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["text_format"] = "",
                    ["xOffset"] = 2,
                },
                ["height"] = 41,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 9,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 120,
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -12,
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
            },
            ["targettarget"] = {
                ["auras"] = {
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                },
                ["customTexts"] = {
                    ["TargetTargetName"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 14,
                        ["text_format"] = "[name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 18,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["enable"] = false,
                    ["growthX"] = "RIGHT",
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["xOffset"] = 2,
                },
                ["height"] = 20,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 21,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["text_format"] = "||cFF007ACC[perpp<%]||r",
                    ["xOffset"] = -2,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["enable"] = false,
                    ["size"] = 20,
                    ["xOffset"] = -22,
                    ["yOffset"] = 1,
                },
                ["threatStyle"] = "GLOW",
                ["width"] = 97,
            },
        },
    },
}::profile::All classes