{
    ["actionbar"] = {
        ["bar1"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "ITCAvantGardeGothicDemi",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["visibility"] = "hide;show;[petbattle] hide; [vehicleui][overridebar][possessbar] show; hide",
        },
        ["bar2"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = "hide;",
        },
        ["bar3"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = "hide;",
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = "hide;",
        },
        ["bar5"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = "hide;",
        },
        ["bar6"] = {
            ["buttonSize"] = 40,
            ["buttonSpacing"] = 0,
            ["buttons"] = 7,
            ["buttonsPerRow"] = 1,
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["professionQuality"] = {
                ["scale"] = 0.4,
                ["xOffset"] = 23,
                ["yOffset"] = -22,
            },
            ["visibility"] = "",
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["buttonsPerRow"] = 10,
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["extraActionButton"] = {
            ["hotkeyFont"] = "ITCAvantGardeGothicDemi",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["stanceBar"] = {
            ["enabled"] = false,
        },
        ["vehicleExitButton"] = {
            ["enable"] = false,
            ["size"] = 50,
        },
        ["zoneActionButton"] = {
            ["clean"] = true,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["horizontalSpacing"] = 1,
            ["size"] = 36,
            ["wrapAfter"] = 10,
        },
        ["debuffs"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["horizontalSpacing"] = 1,
            ["size"] = 36,
            ["wrapAfter"] = 10,
        },
    },
    ["bags"] = {
        ["autoToggle"] = {
            ["trade"] = true,
        },
        ["bagSize"] = 40,
        ["bagWidth"] = 800,
        ["bankSize"] = 40,
        ["bankWidth"] = 500,
        ["clearSearchOnClose"] = true,
        ["countFont"] = "ITCAvantGardeGothicDemi",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 12,
        ["itemInfoFont"] = "ITCAvantGardeGothicDemi",
        ["itemInfoFontOutline"] = "OUTLINE",
        ["itemInfoFontSize"] = 14,
        ["itemLevelCustomColorEnable"] = true,
        ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 12,
        ["scrapIcon"] = true,
        ["split"] = {
            ["bag1"] = true,
            ["bag2"] = true,
            ["bag3"] = true,
            ["bag4"] = true,
            ["bagSpacing"] = 7,
        },
        ["transparent"] = true,
        ["warbandSize"] = 40,
    },
    ["chat"] = {
        ["copyChatLines"] = true,
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 12,
        ["panelBackdrop"] = "LEFT",
        ["panelHeight"] = 253,
        ["panelWidth"] = 500,
        ["tabFont"] = "ITCAvantGardeGothicDemi",
        ["tabFontOutline"] = "OUTLINE",
        ["tabSelectorColor"] = {
            ["b"] = 0.82,
            ["g"] = 0.51,
            ["r"] = 0.09,
        },
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["actionbar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["aurabars"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["auras"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontSize"] = 12,
            ["offsetY"] = -9,
        },
        ["bags"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["bossbutton"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["global"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["nameplates"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["totemtracker"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
        ["unitframe"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["hideNumbers"] = true,
        },
        ["zonebutton"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
        },
    },
    ["databars"] = {
        ["azerite"] = {
            ["enable"] = false,
        },
        ["experience"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["height"] = 15,
            ["width"] = 800,
        },
        ["honor"] = {
            ["enable"] = false,
        },
        ["threat"] = {
            ["enable"] = false,
            ["width"] = 200,
        },
    },
    ["datatexts"] = {
        ["battlePanel"] = {
            ["LeftChatDataPanel"] = {
                [2] = "PvP: Honor Gained",
                [3] = "PvP: Damage Done",
            },
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["panels"] = {
            ["LeftChatDataPanel"] = {
                [3] = "System",
            },
            ["MinimapPanel"] = {
                [1] = "Time",
            },
            ["RightChatDataPanel"] = {
                ["enable"] = false,
            },
        },
    },
    ["general"] = {
        ["addonCompartment"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["hide"] = true,
        },
        ["afk"] = false,
        ["altPowerBar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontOutline"] = "SHADOW",
            ["statusBar"] = "Melli",
        },
        ["autoRepair"] = "PLAYER",
        ["autoTrackReputation"] = true,
        ["backdropcolor"] = {
            ["b"] = 0.11764706671238,
            ["g"] = 0.11764706671238,
            ["r"] = 0.11764706671238,
        },
        ["backdropfadecolor"] = {
            ["b"] = 0.054,
            ["g"] = 0.054,
            ["r"] = 0.054,
        },
        ["bonusObjectivePosition"] = "AUTO",
        ["bottomPanel"] = false,
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontStyle"] = "SHADOW",
        ["fonts"] = {
            ["cooldown"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["errortext"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["mailbody"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["objective"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["size"] = 13,
            },
            ["pvpsubzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["pvpzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["questsmall"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["questtext"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["questtitle"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["talkingtext"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["talkingtitle"] = {
                ["enable"] = true,
                ["font"] = "ITCAvantGardeGothicDemi",
            },
            ["worldsubzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
            ["worldzone"] = {
                ["font"] = "ITCAvantGardeGothicDemi",
                ["outline"] = "SHADOW",
            },
        },
        ["gameMenuScale"] = 0.8,
        ["guildBank"] = {
            ["countFont"] = "ITCAvantGardeGothicDemi",
            ["countFontOutline"] = "SHADOW",
            ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
            ["itemLevelFontOutline"] = "SHADOW",
        },
        ["itemLevel"] = {
            ["itemLevelFont"] = "ITCAvantGardeGothicDemi",
            ["itemLevelFontOutline"] = "SHADOW",
            ["totalLevelFont"] = "ITCAvantGardeGothicDemi",
            ["totalLevelFontOutline"] = "SHADOW",
        },
        ["lootRoll"] = {
            ["nameFont"] = "ITCAvantGardeGothicDemi",
            ["nameFontOutline"] = "SHADOW",
        },
        ["minimap"] = {
            ["icons"] = {
                ["difficulty"] = {
                    ["xOffset"] = 0,
                },
                ["mail"] = {
                    ["scale"] = 1.1,
                    ["texture"] = "Mail1",
                    ["xOffset"] = -3,
                    ["yOffset"] = 2,
                },
            },
            ["locationFont"] = "ITCAvantGardeGothicDemi",
            ["size"] = 220,
        },
        ["objectiveFrameHeight"] = 400,
        ["privateAuras"] = {
            ["duration"] = {
                ["enable"] = false,
            },
            ["enable"] = false,
            ["icon"] = {
                ["size"] = 50,
            },
        },
        ["queueStatus"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["fontOutline"] = "SHADOW",
        },
        ["resurrectSound"] = true,
        ["talkingHeadFrameScale"] = 1,
        ["totems"] = {
            ["sortDirection"] = "DESCENDING",
            ["spacing"] = 1,
        },
    },
    ["movers"] = {
        ["AdditionalPowerMover"] = "BOTTOM,UIParent,BOTTOM,0,215",
        ["AddonCompartmentMover"] = "RIGHT,ElvUI_MinimapHolder,RIGHT,-5,10",
        ["AlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-20",
        ["AltPowerBarMover"] = "BOTTOM,UIParent,BOTTOM,0,230",
        ["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-338,-205",
        ["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-3,-246",
        ["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-247",
        ["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-274",
        ["BossBannerMover"] = "TOP,ElvUIParent,TOP,0,-126",
        ["BossButton"] = "BOTTOM,UIParent,BOTTOM,0,149",
        ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-338,-353",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-225,-2",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-225,-188",
        ["DurabilityFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4",
        ["ElvAB_1"] = "BOTTOM,UIParent,BOTTOM,0,4",
        ["ElvAB_10"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-320,277",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,43",
        ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,83",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,122",
        ["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,162",
        ["ElvAB_6"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,501,2",
        ["ElvAB_7"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-322,368",
        ["ElvAB_8"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-322,338",
        ["ElvAB_9"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-319,307",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-388",
        ["ElvUF_FocusCastbarMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,437,322",
        ["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,461,335",
        ["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,586,-361",
        ["ElvUF_PetCastbarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,587,246",
        ["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,586,264",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,UIParent,BOTTOM,0,380",
        ["ElvUF_PlayerMover"] = "BOTTOM,UIParent,BOTTOM,-329,335",
        ["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,281",
        ["ElvUF_Raid2Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,281",
        ["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,281",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-323",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,329,299",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,329,335",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-460,336",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,329",
        ["ElvUIBankMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,543,202",
        ["EventToastMover"] = "TOP,ElvUIParent,TOP,0,-150",
        ["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-2",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-2",
        ["HonorBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-245",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,2",
        ["LootFrameMover"] = "TOP,UIParent,TOP,280,-460",
        ["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,-1,507",
        ["MicrobarMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-4",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-2,-2",
        ["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,-1,-96",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-163,-325",
        ["PetAB"] = "BOTTOM,UIParent,BOTTOM,0,255",
        ["PowerBarContainerMover"] = "TOP,ElvUIParent,TOP,0,-75",
        ["PrivateAurasMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-225,-248",
        ["PrivateRaidWarningMover"] = "TOP,RaidBossEmoteFrame,TOP,0,0",
        ["QueueStatusMover"] = "BOTTOMRIGHT,ElvUI_MinimapHolder,BOTTOMRIGHT,-5,25",
        ["ReputationBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-244",
        ["RightChatMover"] = "TOPLEFT,UIParent,TOPLEFT,209,-4",
        ["ShiftAB"] = "BOTTOM,UIParent,BOTTOM,-343,4",
        ["SocialMenuMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-187",
        ["ThreatBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-246",
        ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,309",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-30",
        ["TorghastChoiceToggle"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-2",
        ["TotemTrackerMover"] = "BOTTOM,ElvUIParent,BOTTOM,129,389",
        ["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,2,-166",
        ["VehicleLeaveButton"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,570,45",
        ["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-4",
        ["WTChatBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,2,277",
        ["WTCustomEmoteFrameMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-4",
        ["WTMinimapButtonBarAnchor"] = "TOPRIGHT,UIParent,TOPRIGHT,-371,-368",
        ["WTRaidMarkersBarAnchor"] = "BOTTOM,UIParent,BOTTOM,-125,414",
        ["WTSwitchButtonBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-403,-281",
        ["ZoneAbility"] = "BOTTOM,UIParent,BOTTOM,0,95",
    },
    ["nameplates"] = {
        ["colors"] = {
            ["castNoInterruptColor"] = {
                ["a"] = 1,
            },
            ["selection"] = {
                [0] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                [2] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
                [3] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
            },
            ["threat"] = {
                ["badColor"] = {
                    ["b"] = 0.25,
                    ["g"] = 0.25,
                    ["r"] = 0.78,
                },
                ["goodColor"] = {
                    ["b"] = 0.3,
                    ["g"] = 0.67,
                    ["r"] = 0.29,
                },
                ["goodTransition"] = {
                    ["b"] = 0.36,
                    ["g"] = 0.76,
                    ["r"] = 0.85,
                },
            },
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["units"] = {
            ["ENEMY_NPC"] = {
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
            },
            ["ENEMY_PLAYER"] = {
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
                ["portrait"] = {
                    ["classicon"] = false,
                    ["enable"] = true,
                    ["position"] = "LEFT",
                    ["xOffset"] = 0,
                    ["yOffset"] = 0,
                },
            },
        },
    },
    ["tooltip"] = {
        ["font"] = "ITCAvantGardeGothicDemi",
        ["headerFont"] = "ITCAvantGardeGothicDemi",
        ["headerFontSize"] = 12,
        ["healthBar"] = {
            ["font"] = "ITCAvantGardeGothicDemi",
            ["height"] = 8,
        },
        ["itemCount"] = {
            ["bank"] = true,
            ["stack"] = true,
        },
        ["visibility"] = {
            ["combatOverride"] = "SHIFT",
        },
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["aurabar_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["castClassColor"] = true,
            ["castColor"] = {
                ["a"] = 1,
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["castbar_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["classpower_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["colorhealthbyvalue"] = false,
            ["customcastbarbackdrop"] = true,
            ["customclasspowerbackdrop"] = true,
            ["customhealthbackdrop"] = true,
            ["custompowerbackdrop"] = true,
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["enable"] = false,
                },
            },
            ["health"] = {
                ["b"] = 0,
                ["g"] = 0,
                ["r"] = 0,
            },
            ["health_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["health_backdrop_dead"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["healthclass"] = true,
            ["power_backdrop"] = {
                ["b"] = 0.05882353335619,
                ["g"] = 0.05882353335619,
                ["r"] = 0.05882353335619,
            },
            ["reaction"] = {
                [1] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                [2] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.23529413342476,
                    ["r"] = 0.78431379795074,
                },
                [4] = {
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.78431379795074,
                },
                [5] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
                [6] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
                [7] = {
                    ["b"] = 0.23529413342476,
                    ["g"] = 0.78431379795074,
                    ["r"] = 0.23529413342476,
                },
            },
            ["useDeadBackdrop"] = true,
        },
        ["font"] = "ITCAvantGardeGothicDemi",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 16,
        ["statusbar"] = "Melli",
        ["units"] = {
            ["arena"] = {
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["sizeOverride"] = 29,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = 14,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["height"] = 16,
                    ["positionsGroup"] = {
                        ["xOffset"] = 30,
                        ["yOffset"] = -17,
                    },
                    ["width"] = 191,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -12,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -12,
                    },
                },
                ["debuffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["sizeOverride"] = 29,
                    ["spacing"] = 0,
                },
                ["growthDirection"] = "UP",
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 0,
                    ["yOffset"] = -23,
                },
                ["height"] = 60,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:abbrev:long]",
                    ["yOffset"] = 9,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -23,
                },
                ["pvpTrinket"] = {
                    ["size"] = 60,
                    ["xOffset"] = 0,
                },
                ["spacing"] = 42,
                ["width"] = 250,
            },
            ["assist"] = {
                ["enable"] = false,
            },
            ["boss"] = {
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = false,
                    ["isAuraImportantPlayer"] = false,
                    ["isAuraRaidPlayerDispellable"] = false,
                    ["maxDuration"] = 300,
                    ["priority"] = "Blacklist,Whitelist,Dispellable,TurtleBuffs",
                    ["sizeOverride"] = 38,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["height"] = 16,
                    ["positionsGroup"] = {
                        ["xOffset"] = 30,
                        ["yOffset"] = -17,
                    },
                    ["width"] = 191,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -13,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -11,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["desaturate"] = false,
                    ["isAuraCrowdControl"] = true,
                    ["maxDuration"] = 300,
                    ["perrow"] = 5,
                    ["sizeOverride"] = 38,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["growthDirection"] = "UP",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 0,
                    ["yOffset"] = -23,
                },
                ["height"] = 40,
                ["infoPanel"] = {
                    ["height"] = 17,
                },
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:abbrev:long]",
                    ["yOffset"] = 9,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -23,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "TOPLEFT",
                },
                ["spacing"] = 30,
                ["width"] = 200,
            },
            ["focus"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["detachedWidth"] = 270,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                    ["maxBars"] = 6,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["enable"] = false,
                    ["height"] = 8,
                    ["hideName"] = true,
                    ["hideTime"] = true,
                    ["icon"] = false,
                    ["insideInfoPanel"] = false,
                    ["width"] = 125,
                },
                ["customTexts"] = {
                    ["FocusName"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "CENTER",
                        ["size"] = 14,
                        ["text_format"] = "[name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 20,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "BUFFS",
                    ["enable"] = false,
                    ["growthX"] = "RIGHT",
                    ["isAuraBigDefensive"] = false,
                    ["isAuraExternalDefensive"] = false,
                    ["isAuraPlayer"] = false,
                    ["isAuraRaid"] = false,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                },
                ["disableMouseoverGlow"] = true,
                ["disableTargetGlow"] = true,
                ["healPrediction"] = {
                    ["enable"] = false,
                },
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["xOffset"] = 2,
                },
                ["height"] = 23,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 21,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["text_format"] = "||cFF007ACC[perpp<%]||r",
                    ["xOffset"] = -2,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["size"] = 20,
                    ["xOffset"] = -22,
                    ["yOffset"] = 1,
                },
                ["width"] = 125,
            },
            ["party"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 10,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["numrows"] = 3,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 21,
                    ["spacing"] = 0,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["GroupName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[name:abbrev:long]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 35,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthY"] = "DOWN",
                    ["numrows"] = 2,
                    ["perrow"] = 3,
                    ["sizeOverride"] = 35,
                    ["spacing"] = 0,
                    ["yOffset"] = 1,
                },
                ["groupBy"] = "ROLE",
                ["health"] = {
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 70,
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["text_format"] = "",
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["xOffset"] = 1,
                    ["yOffset"] = 7,
                },
                ["rdebuffs"] = {
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["position"] = "TOPLEFT",
                    ["size"] = 14,
                    ["xOffset"] = 2,
                    ["yOffset"] = -6,
                },
                ["sortDir"] = "DESC",
                ["verticalSpacing"] = 7,
                ["width"] = 150,
            },
            ["pet"] = {
                ["castbar"] = {
                    ["enable"] = false,
                    ["iconSize"] = 32,
                    ["width"] = 130,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["enable"] = true,
                },
                ["disableTargetGlow"] = false,
                ["height"] = 30,
                ["infoPanel"] = {
                    ["height"] = 14,
                },
                ["power"] = {
                    ["enable"] = false,
                },
            },
            ["player"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["attachTo"] = "FRAME",
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["customTimeFont"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["height"] = 8,
                    ["hideName"] = true,
                    ["hideTime"] = true,
                    ["icon"] = false,
                    ["insideInfoPanel"] = false,
                    ["width"] = 300,
                },
                ["classbar"] = {
                    ["enable"] = false,
                    ["height"] = 14,
                },
                ["customTexts"] = {
                    ["Absorbs"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 16,
                        ["text_format"] = "[absorbs:shortvalue]",
                        ["xOffset"] = -3,
                        ["yOffset"] = 0,
                    },
                    ["HP"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 16,
                        ["text_format"] = "[perhp<%] I [health:current:shortvalue]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -33,
                    },
                },
                ["debuffs"] = {
                    ["attachTo"] = "BUFFS",
                    ["enable"] = false,
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["position"] = "RIGHT",
                    ["text_format"] = "",
                },
                ["height"] = 45,
                ["partyIndicator"] = {
                    ["enable"] = false,
                },
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["position"] = "LEFT",
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
            },
            ["raid1"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontOutline"] = "SHADOW",
                    ["countFontSize"] = 9,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["isAuraPlayer"] = true,
                    ["numrows"] = 3,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 16,
                    ["spacing"] = 0,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 24,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 10,
                    ["enable"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 32,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 5,
                ["growthDirection"] = "RIGHT_UP",
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["numGroups"] = 4,
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                    ["icon"] = {
                        ["size"] = 20,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["enable"] = false,
                    ["size"] = 16,
                },
                ["rdebuffs"] = {
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["position"] = "TOPLEFT",
                    ["size"] = 12,
                    ["xOffset"] = 0,
                    ["yOffset"] = -2,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["raid2"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontOutline"] = "SHADOW",
                    ["countFontSize"] = 9,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["isAuraPlayer"] = true,
                    ["numrows"] = 3,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 16,
                    ["spacing"] = 0,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 26,
                    },
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 24,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 10,
                    ["enable"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 32,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 5,
                ["growthDirection"] = "RIGHT_UP",
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["numGroups"] = 6,
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                    ["icon"] = {
                        ["size"] = 20,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["enable"] = false,
                    ["size"] = 16,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["enable"] = true,
                    ["position"] = "TOPLEFT",
                    ["size"] = 12,
                    ["xOffset"] = 0,
                    ["yOffset"] = -2,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["raid3"] = {
                ["CombatIcon"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["size"] = 12,
                },
                ["auras"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontOutline"] = "SHADOW",
                    ["countFontSize"] = 9,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["growthY"] = "DOWN",
                    ["isAuraPlayer"] = true,
                    ["numrows"] = 3,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 16,
                    ["spacing"] = 0,
                },
                ["classbar"] = {
                    ["height"] = 6,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 26,
                    },
                    ["RaidName"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[name:abbrev:medium]",
                        ["xOffset"] = 10,
                        ["yOffset"] = 24,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["countFontSize"] = 10,
                    ["enable"] = true,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Dispellable,RaidDebuffs,CCDebuffs",
                    ["sizeOverride"] = 32,
                    ["spacing"] = 0,
                    ["yOffset"] = -1,
                },
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 5,
                ["growthDirection"] = "RIGHT_UP",
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = -48,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 5,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 12,
                    ["yOffset"] = 9,
                },
                ["orientation"] = "LEFT",
                ["phaseIndicator"] = {
                    ["xOffset"] = -30,
                },
                ["power"] = {
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["privateAuras"] = {
                    ["duration"] = {
                        ["enable"] = true,
                    },
                    ["icon"] = {
                        ["size"] = 20,
                    },
                },
                ["raidicon"] = {
                    ["attachTo"] = "BOTTOMLEFT",
                    ["enable"] = false,
                    ["size"] = 16,
                },
                ["rdebuffs"] = {
                    ["enable"] = true,
                    ["font"] = "ITCAvantGardeGothicDemi",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "CENTER",
                    ["size"] = 30,
                },
                ["resurrectIcon"] = {
                    ["xOffset"] = 30,
                },
                ["roleIcon"] = {
                    ["enable"] = true,
                    ["position"] = "TOPLEFT",
                    ["size"] = 12,
                    ["xOffset"] = 0,
                    ["yOffset"] = -2,
                },
                ["verticalSpacing"] = 0,
                ["width"] = 96,
            },
            ["tank"] = {
                ["enable"] = false,
            },
            ["target"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["isAuraImportant"] = true,
                    ["isAuraImportantPlayer"] = true,
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                },
                ["auras"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["enable"] = false,
                    ["filter"] = "HELPFUL",
                    ["isAuraCrowdControl"] = false,
                    ["isAuraCrowdControlPlayer"] = false,
                    ["perrow"] = 8,
                    ["priority"] = "",
                    ["sizeOverride"] = 0,
                    ["xOffset"] = 0,
                },
                ["buffs"] = {
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["numrows"] = 2,
                    ["perrow"] = 3,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                    ["sizeOverride"] = 32,
                    ["spacing"] = 0,
                    ["yOffset"] = 6,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontSize"] = 11,
                    },
                    ["height"] = 16,
                    ["insideInfoPanel"] = false,
                },
                ["customTexts"] = {
                    ["HP"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[health:current:shortvalue] I [perhp<%]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -33,
                    },
                    ["Resources"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[powercolor][perpp]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -11,
                    },
                    ["TargetName"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 15,
                        ["text_format"] = "[name:abbrev:long]",
                        ["xOffset"] = -3,
                        ["yOffset"] = 20,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "ITCAvantGardeGothicDemi",
                    ["growthX"] = "RIGHT",
                    ["maxDuration"] = 0,
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                    ["sizeOverride"] = 32,
                    ["sourceText"] = {
                        ["font"] = "ITCAvantGardeGothicDemi",
                    },
                    ["spacing"] = 0,
                    ["yOffset"] = -2,
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["text_format"] = "",
                    ["xOffset"] = 2,
                },
                ["height"] = 45,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 9,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 6,
                    ["position"] = "RIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = -12,
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
            },
            ["targettarget"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["isAuraBigDefensive"] = true,
                    ["isAuraExternalDefensive"] = true,
                    ["isAuraExternalDefensivePlayer"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,NonPersonal",
                },
                ["customTexts"] = {
                    ["TargetTargetName"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "ITCAvantGardeGothicDemi",
                        ["fontOutline"] = "SHADOW",
                        ["justifyH"] = "CENTER",
                        ["size"] = 14,
                        ["text_format"] = "[name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 20,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["enable"] = false,
                    ["growthX"] = "RIGHT",
                    ["isAuraRaid"] = false,
                    ["isAuraRaidPlayer"] = false,
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,NonPersonal",
                },
                ["disableMouseoverGlow"] = true,
                ["health"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["xOffset"] = 2,
                },
                ["height"] = 23,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 21,
                },
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["attachTextTo"] = "InfoPanel",
                    ["enable"] = false,
                    ["height"] = 22,
                    ["text_format"] = "||cFF007ACC[perpp<%]||r",
                    ["xOffset"] = -2,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
                ["threatStyle"] = "GLOW",
                ["width"] = 125,
            },
        },
    },
}::profile::All classes