
CursorTrail_Config = {
["ProfileOptions"] = {
["bSaveOnOkay"] = false,
["bConfirmDelete"] = true,
["bConfirmCopy"] = true,
["bUseAccountProfile"] = true,
},
["NewFeaturesSeen"] = {
},
["Profiles"] = {
["_SelectedName"] = {
["ALL_CHARACTERS"] = "all classes",
},
["all classes"] = {
["MasterScale"] = 1,
["ConfigVersion"] = 2,
["Layers"] = {
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = true,
["UserShowMouseLook"] = false,
["ModelID"] = 1417024,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["UserOfsX"] = 0,
["UserScale"] = 0.5,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["UserRotZ"] = 0,
["ShapeColorG"] = 1,
["ShapeSparkle"] = false,
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["ShapeFileName"] = "",
},
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = false,
["UserShowMouseLook"] = false,
["ModelID"] = 0,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["ShapeFileName"] = "Interface\\Addons\\CursorTrail\\Media\\Ring 1.tga",
["UserScale"] = 1,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["ShapeSparkle"] = false,
["ShapeColorG"] = 1,
["UserRotZ"] = 0,
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["UserOfsX"] = 0,
},
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = false,
["UserShowMouseLook"] = false,
["ModelID"] = 0,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["ShapeFileName"] = "Interface\\Addons\\CursorTrail\\Media\\Ring 1.tga",
["UserScale"] = 1,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["ShapeSparkle"] = false,
["ShapeColorG"] = 1,
["UserRotZ"] = 0,
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["UserOfsX"] = 0,
},
},
},
},
["ChangelogVersionSeen"] = "11.1.7.2",
["ProfileBackups"] = {
["@Login"] = {
["_SelectedName"] = {
["ALL_CHARACTERS"] = "all classes",
},
["all classes"] = {
["MasterScale"] = 1,
["ConfigVersion"] = 2,
["Layers"] = {
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = true,
["UserShowMouseLook"] = false,
["ModelID"] = 1417024,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["UserOfsX"] = 0,
["UserScale"] = 0.5,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["UserRotZ"] = 0,
["ShapeColorG"] = 1,
["ShapeFileName"] = "",
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["ShapeSparkle"] = false,
},
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = false,
["UserShowMouseLook"] = false,
["ModelID"] = 0,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["ShapeFileName"] = "Interface\\Addons\\CursorTrail\\Media\\Ring 1.tga",
["UserScale"] = 1,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["ShapeSparkle"] = false,
["ShapeColorG"] = 1,
["UserOfsX"] = 0,
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["UserRotZ"] = 0,
},
{
["Strata"] = "HIGH",
["ShapeColorA"] = 1,
["IsLayerEnabled"] = false,
["UserShowMouseLook"] = false,
["ModelID"] = 0,
["UserRotX"] = 0,
["ShapeColorB"] = 1,
["ShapeFileName"] = "Interface\\Addons\\CursorTrail\\Media\\Ring 1.tga",
["UserScale"] = 1,
["UserShadowAlpha"] = 0,
["UserRotY"] = 0,
["UserOfsY"] = 0,
["ShapeSparkle"] = false,
["ShapeColorG"] = 1,
["UserOfsX"] = 0,
["UserAlpha"] = 1,
["UserOfsZ"] = 0,
["UserShowOnlyInCombat"] = false,
["FadeOut"] = false,
["ShapeColorR"] = 1,
["UserRotZ"] = 0,
},
},
},
},
},
}
