
ElvDB = {
["profileKeys"] = {
["Бимладен - Ревущий фьорд"] = "All classes",
["Вольтчара - Свежеватель Душ"] = "Default",
},
["DisabledAddOns"] = {
},
["serverID"] = {
[1604] = {
["Свежеватель Душ"] = true,
},
[1615] = {
["Ревущий фьорд"] = true,
},
},
["class"] = {
["Ревущий фьорд"] = {
["Бимладен"] = "DRUID",
},
["Свежеватель Душ"] = {
["Вольтчара"] = "SHAMAN",
},
},
["profiles"] = {
["Default"] = {
["convertPages"] = true,
["dbConverted"] = 13.75,
["chat"] = {
["panelSnapLeftID"] = 1,
},
["actionbar"] = {
["bar6"] = {
["enabled"] = true,
["buttonsPerRow"] = 6,
["buttons"] = 6,
},
["microbar"] = {
["buttons"] = 11,
},
["bar5"] = {
["enabled"] = false,
["buttonsPerRow"] = 12,
["buttons"] = 12,
},
},
},
["All classes"] = {
["databars"] = {
["threat"] = {
["enable"] = false,
["font"] = "ITCAvantGardeGothicDemi",
},
["honor"] = {
["enable"] = false,
["font"] = "ITCAvantGardeGothicDemi",
},
["reputation"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["statusbar"] = "Melli Dark",
["experience"] = {
["height"] = 18,
["textFormat"] = "CURPERCREM",
["width"] = 760,
["font"] = "ITCAvantGardeGothicDemi",
["orientation"] = "HORIZONTAL",
["showLevel"] = true,
},
["azerite"] = {
["enable"] = false,
["width"] = 8,
["font"] = "ITCAvantGardeGothicDemi",
["orientation"] = "VERTICAL",
["height"] = 203,
},
},
["general"] = {
["gameMenuScale"] = 0.8,
["valuecolor"] = {
["b"] = 0.04,
["g"] = 0.49,
["r"] = 1,
},
["talkingHeadFrameScale"] = 0.75,
["guildBank"] = {
["itemLevelFont"] = "ITCAvantGardeGothicDemi",
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["itemLevelFontOutline"] = "OUTLINE",
},
["bottomPanel"] = false,
["itemLevel"] = {
["totalLevelFont"] = "ITCAvantGardeGothicDemi",
["itemLevelFontSize"] = 11,
["itemLevelFont"] = "ITCAvantGardeGothicDemi",
},
["objectiveFrameAutoHideInKeystone"] = true,
["customGlow"] = {
["lines"] = 4,
["style"] = "Autocast Shine",
},
["totems"] = {
["spacing"] = 2,
["sortDirection"] = "DESCENDING",
["size"] = 37,
},
["font"] = "ITCAvantGardeGothicDemi",
["altPowerBar"] = {
["font"] = "ITCAvantGardeGothicDemi",
["fontOutline"] = "SHADOWOUTLINE",
},
["fontSize"] = 11,
["queueStatus"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["afk"] = false,
["autoRepair"] = "PLAYER",
["minimap"] = {
["timeFont"] = "ITCAvantGardeGothicDemi",
["icons"] = {
["crafting"] = {
["position"] = "BOTTOM",
},
["mail"] = {
["position"] = "BOTTOMLEFT",
["texture"] = "Mail1",
},
["tracking"] = {
["position"] = "TOPRIGHT",
},
["classHall"] = {
["position"] = "TOPRIGHT",
},
},
["locationFont"] = "ITCAvantGardeGothicDemi",
["locationFontOutline"] = "SHADOW",
},
["resurrectSound"] = true,
["objectiveFrameHeight"] = 560,
["lootRoll"] = {
["nameFont"] = "ITCAvantGardeGothicDemi",
["nameFontOutline"] = "SHADOWOUTLINE",
},
["debuffColors"] = {
["BadDispel"] = {
["r"] = 0.05098039656877518,
["g"] = 0.8509804606437683,
["b"] = 0.9411765336990356,
},
["Magic"] = {
["g"] = 0.6000000238418579,
["r"] = 0.2000000178813934,
},
},
["fonts"] = {
["errortext"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
["size"] = 14,
},
["pvpsubzone"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["objective"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
["outline"] = "OUTLINE",
},
["worldsubzone"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["questsmall"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
["enable"] = true,
["size"] = 12,
},
["pvpzone"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["questtext"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
["enable"] = true,
["size"] = 13,
},
["worldzone"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["questtitle"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
["enable"] = true,
["size"] = 14,
},
["talkingtitle"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
},
["mailbody"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
},
["cooldown"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
},
["talkingtext"] = {
["outline"] = "OUTLINE",
["font"] = "ITCAvantGardeGothicDemi",
},
},
["addonCompartment"] = {
["font"] = "ITCAvantGardeGothicDemi",
["hide"] = true,
},
},
["bags"] = {
["itemLevelFont"] = "ITCAvantGardeGothicDemi",
["itemInfoFont"] = "ITCAvantGardeGothicDemi",
["itemLevelFontSize"] = 11,
["bagWidth"] = 455,
["countFontOutline"] = "SHADOWOUTLINE",
["bagBar"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["bankWidth"] = 700,
["itemInfoFontSize"] = 11,
["bankSize"] = 37,
["itemLevelFontOutline"] = "SHADOWOUTLINE",
["countFontSize"] = 11,
["itemInfoFontOutline"] = "SHADOWOUTLINE",
["countFont"] = "ITCAvantGardeGothicDemi",
["bagSize"] = 35,
["vendorGrays"] = {
["enable"] = true,
["interval"] = 0.1,
},
["cooldown"] = {
["override"] = true,
["fonts"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
["fontOutline"] = "SHADOWOUTLINE",
},
},
["clearSearchOnClose"] = true,
},
["auras"] = {
["debuffs"] = {
["horizontalSpacing"] = 1,
["timeYOffset"] = -2,
["countFont"] = "ITCAvantGardeGothicDemi",
["barTexture"] = "Melli Dark",
["countFontOutline"] = "OUTLINE",
["timeFontOutline"] = "OUTLINE",
["sortMethod"] = "NAME",
["countFontSize"] = 11,
["verticalSpacing"] = 15,
["timeFont"] = "ITCAvantGardeGothicDemi",
["timeFontSize"] = 11,
},
["buffs"] = {
["horizontalSpacing"] = 1,
["countYOffset"] = 2,
["timeYOffset"] = -2,
["countFont"] = "ITCAvantGardeGothicDemi",
["timeFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["timeFontOutline"] = "OUTLINE",
["countFontSize"] = 11,
["verticalSpacing"] = 15,
["timeFontSize"] = 11,
["barTexture"] = "Melli Dark",
},
["cooldown"] = {
["expiringColor"] = {
["g"] = 0.003921568627451,
},
["threshold"] = 5,
["override"] = true,
},
},
["dbConverted"] = 13.75,
["WeakAuras"] = {
["cooldown"] = {
["hideBlizzard"] = true,
["fonts"] = {
["font"] = "ITCAvantGardeGothicDemi",
["fontOutline"] = "SHADOWOUTLINE",
},
["reverse"] = true,
},
},
["movers"] = {
["ElvUF_FocusCastbarMover"] = "TOP,ElvUIParent,TOP,0,-245",
["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-178,-1",
["TargetPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,295,247",
["MawBuffsBelowMinimapMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,308",
["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,196,66",
["LootFrameMover"] = "TOP,ElvUIParent,TOP,0,-423",
["ZoneAbility"] = "BOTTOM,ElvUIParent,BOTTOM,-196,66",
["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,736",
["DurabilityFrameMover"] = "BOTTOM,ElvUIParent,BOTTOM,-202,380",
["ElvUF_PetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-221,252",
["VehicleSeatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,451,1",
["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-455,248",
["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-423",
["QueueStatusMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-145",
["MirrorTimer1Mover"] = "BOTTOM,UIParent,BOTTOM,0,375",
["ElvUF_Raid1Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,208",
["TalkingHeadFrameMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-248,103",
["AzeriteBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,411,1",
["ElvUF_Raid2Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,208",
["AddonCompartmentMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-156",
["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-53,-204",
["BNETMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,-239",
["ShiftAB"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,1076",
["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,295,213",
["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,263",
["ElvAB_7"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,369",
["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-1,-96",
["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,1,685",
["TopCenterContainerMover"] = "BOTTOM,UIParent,BOTTOM,0,4",
["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,-294,160",
["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,1",
["GMMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,-239",
["MirrorTimer3Mover"] = "BOTTOM,UIParent,BOTTOM,0,415",
["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,455,248",
["MicrobarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-408,1",
["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-1",
["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,295,248",
["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-295,248",
["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,0,-124",
["MirrorTimer2Mover"] = "BOTTOM,UIParent,BOTTOM,0,394",
["AltPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,152",
["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,1",
["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,34",
["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-15,-274",
["ElvUIBankMover"] = "TOP,ElvUIParent,TOP,-243,-200",
["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,99",
["TotemBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,204,4",
["ArtifactBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,412,1",
["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,67",
["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,132",
["VehicleLeaveButton"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-146,-202",
["PrivateAurasMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-113,-202",
["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,2,277",
["ElvUF_Raid3Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,208",
["TotemTrackerMover"] = "BOTTOM,ElvUIParent,BOTTOM,138,283",
["VOICECHAT"] = "TOPLEFT,UIParent,TOPLEFT,4,-183",
["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-477,-337",
["HonorBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,421,1",
["ElvAB_6"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,419,1",
["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,338",
["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,1,621",
["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-178,-202",
["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,556,188",
["ElvAB_13"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,1,205",
["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,555,335",
["AlertFrameMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-555,279",
["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-178,-151",
["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-1,-1",
},
["convertPages"] = true,
["tooltip"] = {
["fontOutline"] = "SHADOWOUTLINE",
["healthBar"] = {
["font"] = "ITCAvantGardeGothicDemi",
["fontOutline"] = "SHADOWOUTLINE",
["height"] = 6,
["text"] = false,
},
["font"] = "ITCAvantGardeGothicDemi",
["visibility"] = {
["combatOverride"] = "ALT",
},
["smallTextFontSize"] = 11,
["headerFont"] = "ITCAvantGardeGothicDemi",
["alwaysShowRealm"] = true,
["headerFontSize"] = 11,
["headerFontOutline"] = "SHADOWOUTLINE",
["itemQuality"] = true,
["textFontSize"] = 11,
},
["unitframe"] = {
["fontSize"] = 12,
["smoothbars"] = true,
["units"] = {
["tank"] = {
["enable"] = false,
},
["targettargettarget"] = {
["debuffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["buffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
},
["party"] = {
["pvpclassificationindicator"] = {
["enable"] = false,
},
["verticalSpacing"] = 7,
["growthDirection"] = "DOWN_LEFT",
["groupBy"] = "ROLE",
["readycheckIcon"] = {
["position"] = "CENTER",
["size"] = 30,
},
["sortDir"] = "DESC",
["petsGroup"] = {
["width"] = 60,
["disableTargetGlow"] = false,
["xOffset"] = 0,
["yOffset"] = -1,
["disableFocusGlow"] = false,
["name"] = {
["text_format"] = "",
},
["height"] = 12,
["anchorPoint"] = "BOTTOMRIGHT",
},
["classbar"] = {
["height"] = 5,
["altPowerTextFormat"] = " ",
},
["targetsGroup"] = {
["disableTargetGlow"] = false,
["disableFocusGlow"] = false,
},
["customTexts"] = {
["GroupName"] = {
["attachTextTo"] = "Frame",
["xOffset"] = 12,
["text_format"] = "[name:short]",
["yOffset"] = 26,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "SHADOW",
["enable"] = false,
["size"] = 12,
},
["GroupNameStatus"] = {
["attachTextTo"] = "Health",
["xOffset"] = 0,
["text_format"] = "[dead][offline]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "OUTLINE",
["enable"] = true,
["size"] = 14,
},
},
["healPrediction"] = {
["enable"] = true,
["absorbStyle"] = "WRAPPED",
},
["infoPanel"] = {
["height"] = 12,
},
["name"] = {
["position"] = "TOPLEFT",
["xOffset"] = 12,
["text_format"] = "[name:short]",
["yOffset"] = 6,
},
["height"] = 63,
["buffs"] = {
["countFontSize"] = 14,
["sizeOverride"] = 31,
["growthX"] = "LEFT",
["enable"] = true,
["countYOffset"] = 0,
["yOffset"] = -32,
["anchorPoint"] = "TOPRIGHT",
["countXOffset"] = 1,
["spacing"] = 0,
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,TurtleBuffs,Personals",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 2,
["clickThrough"] = true,
},
["raidicon"] = {
["attachTo"] = "BOTTOMLEFT",
["xOffset"] = 2,
["yOffset"] = 10,
},
["horizontalSpacing"] = 1,
["rdebuffs"] = {
["enable"] = false,
["duration"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
},
["font"] = "ITCAvantGardeGothicDemi",
["stack"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
},
["xOffset"] = -52,
["size"] = 28,
},
["resurrectIcon"] = {
["attachTo"] = "RIGHT",
["xOffset"] = -5,
},
["debuffs"] = {
["countFontSize"] = 14,
["sizeOverride"] = 31,
["countYOffset"] = 0,
["yOffset"] = 2,
["anchorPoint"] = "TOPRIGHT",
["countXOffset"] = 1,
["spacing"] = 0,
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
["growthY"] = "DOWN",
["numrows"] = 2,
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 2,
["maxDuration"] = 600,
},
["roleIcon"] = {
["yOffset"] = -5,
["position"] = "TOPLEFT",
["xOffset"] = 2,
},
["power"] = {
["text_format"] = "",
["yOffset"] = 2,
["position"] = "BOTTOMRIGHT",
["height"] = 6,
},
["summonIcon"] = {
["attachTo"] = "RIGHT",
["xOffset"] = -5,
["yOffset"] = 3,
},
["width"] = 130,
["health"] = {
["position"] = "BOTTOMLEFT",
["xOffset"] = 0,
["text_format"] = "",
["yOffset"] = 2,
},
["orientation"] = "MIDDLE",
["buffIndicator"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
},
["focus"] = {
["debuffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 20,
["enable"] = false,
["priority"] = "Blacklist,Personal,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 4,
["attachTo"] = "BUFFS",
},
["disableTargetGlow"] = true,
["CombatIcon"] = {
["enable"] = false,
},
["aurabar"] = {
["maxBars"] = 6,
["attachTo"] = "FRAME",
},
["threatStyle"] = "NONE",
["castbar"] = {
["enable"] = false,
["overlayOnFrame"] = "Health",
["icon"] = false,
["customTimeFont"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["customTextFont"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
["width"] = 400,
["height"] = 8,
},
["customTexts"] = {
["TargetName"] = {
["attachTextTo"] = "Health",
["enable"] = true,
["text_format"] = "[name:short]",
["yOffset"] = 16,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["xOffset"] = 0,
["size"] = 13,
},
},
["width"] = 100,
["name"] = {
["position"] = "TOPLEFT",
["text_format"] = " ",
},
["height"] = 15,
["buffs"] = {
["priority"] = "Blacklist,Personal,PlayerBuffs,Dispellable",
["countFont"] = "ITCAvantGardeGothicDemi",
},
["power"] = {
["enable"] = false,
["height"] = 5,
},
["raidicon"] = {
["attachTo"] = "LEFT",
["size"] = 15,
["xOffset"] = -15,
["yOffset"] = 1,
},
},
["target"] = {
["debuffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 30,
["growthX"] = "RIGHT",
["anchorPoint"] = "TOPLEFT",
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Personal,RaidDebuffs,CCDebuffs,Friendly:Dispellable",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 3,
["attachTo"] = "FRAME",
},
["CombatIcon"] = {
["enable"] = false,
},
["customTexts"] = {
["TargetName"] = {
["attachTextTo"] = "Power",
["xOffset"] = 0,
["text_format"] = "[name:abbrev]",
["yOffset"] = 28,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "RIGHT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 13,
},
["HP"] = {
["attachTextTo"] = "Health",
["xOffset"] = 3,
["text_format"] = "[health:current:shortvalue] I [health:percent]",
["yOffset"] = -25,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 14,
},
["TargetPower"] = {
["attachTextTo"] = "Health",
["xOffset"] = 0,
["text_format"] = "[powercolor][perpp]",
["yOffset"] = -25,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "RIGHT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 13,
},
},
["name"] = {
["attachTextTo"] = "Frame",
["position"] = "RIGHT",
["text_format"] = "",
},
["height"] = 30,
["buffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 30,
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,Personal,nonPersonal",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 5,
},
["raidicon"] = {
["enable"] = false,
},
["aurabar"] = {
["enable"] = false,
["attachTo"] = "FRAME",
},
["castbar"] = {
["width"] = 250,
},
["width"] = 250,
["raidRoleIcons"] = {
["enable"] = false,
},
["health"] = {
["text_format"] = "",
["yOffset"] = -14,
},
["power"] = {
["text_format"] = "",
["detachFromFrame"] = true,
["height"] = 5,
},
},
["raid2"] = {
["pvpclassificationindicator"] = {
["enable"] = false,
},
["numGroups"] = 6,
["growthDirection"] = "RIGHT_UP",
["readycheckIcon"] = {
["position"] = "CENTER",
["size"] = 18,
},
["groupSpacing"] = 3,
["classbar"] = {
["altPowerTextFormat"] = " ",
["height"] = 5,
},
["customTexts"] = {
["RaidNameStatus"] = {
["attachTextTo"] = "Health",
["xOffset"] = 0,
["text_format"] = "[status]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 12,
},
["RaidName"] = {
["attachTextTo"] = "Health",
["xOffset"] = 13,
["text_format"] = "[name:veryshort]",
["yOffset"] = 20,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 11,
},
},
["healPrediction"] = {
["enable"] = true,
["absorbStyle"] = "WRAPPED",
},
["name"] = {
["position"] = "LEFT",
["xOffset"] = 9,
["text_format"] = "",
["yOffset"] = 20,
},
["height"] = 45,
["buffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 23,
["xOffset"] = -36,
["anchorPoint"] = "RIGHT",
["clickThrough"] = true,
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,TurtleBuffs",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 1,
["enable"] = true,
},
["raidicon"] = {
["attachTo"] = "TOPLEFT",
["size"] = 15,
["xOffset"] = 60,
["yOffset"] = 6,
},
["rdebuffs"] = {
["fontSize"] = 12,
["enable"] = true,
["duration"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
},
["yOffset"] = 12,
["font"] = "ITCAvantGardeGothicDemi",
["xOffset"] = -12,
["stack"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
["yOffset"] = 1,
},
},
["resurrectIcon"] = {
["attachTo"] = "RIGHT",
["xOffset"] = -5,
},
["debuffs"] = {
["countFontSize"] = 17,
["sizeOverride"] = 45,
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 4,
},
["roleIcon"] = {
["enable"] = true,
["yOffset"] = 0,
["position"] = "TOPLEFT",
["xOffset"] = 0,
},
["power"] = {
["enable"] = true,
},
["width"] = 82,
["health"] = {
["position"] = "BOTTOMLEFT",
["text_format"] = "",
},
},
["focustarget"] = {
["debuffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["buffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
},
["pet"] = {
["debuffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["castbar"] = {
["enable"] = false,
["width"] = 100,
["height"] = 15,
},
["width"] = 100,
["power"] = {
["height"] = 5,
},
["height"] = 20,
["buffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["name"] = {
["text_format"] = " ",
["yOffset"] = 2,
},
["raidicon"] = {
["enable"] = false,
},
},
["raid3"] = {
["pvpclassificationindicator"] = {
["enable"] = false,
},
["growthDirection"] = "RIGHT_UP",
["readycheckIcon"] = {
["position"] = "CENTER",
["size"] = 18,
},
["groupSpacing"] = 3,
["classbar"] = {
["altPowerTextFormat"] = " ",
["height"] = 5,
},
["customTexts"] = {
["RaidNameStatus"] = {
["attachTextTo"] = "Health",
["enable"] = true,
["text_format"] = "[status]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["xOffset"] = 0,
["size"] = 12,
},
["RaidName"] = {
["attachTextTo"] = "Health",
["xOffset"] = 13,
["text_format"] = "[name:veryshort]",
["yOffset"] = 20,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 11,
},
},
["healPrediction"] = {
["enable"] = true,
["absorbStyle"] = "WRAPPED",
},
["name"] = {
["position"] = "LEFT",
["xOffset"] = 9,
["text_format"] = "",
["yOffset"] = 20,
},
["height"] = 45,
["buffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 23,
["xOffset"] = -36,
["anchorPoint"] = "RIGHT",
["clickThrough"] = true,
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,TurtleBuffs",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 1,
["enable"] = true,
},
["raidicon"] = {
["attachTo"] = "TOPLEFT",
["yOffset"] = 6,
["xOffset"] = 60,
["size"] = 15,
},
["rdebuffs"] = {
["fontSize"] = 12,
["enable"] = true,
["duration"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
},
["yOffset"] = 12,
["font"] = "ITCAvantGardeGothicDemi",
["xOffset"] = -12,
["stack"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
["yOffset"] = 1,
},
},
["resurrectIcon"] = {
["attachTo"] = "RIGHT",
["xOffset"] = -5,
},
["debuffs"] = {
["countFontSize"] = 17,
["sizeOverride"] = 45,
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 4,
},
["roleIcon"] = {
["enable"] = true,
["yOffset"] = 0,
["position"] = "TOPLEFT",
["xOffset"] = 0,
},
["power"] = {
["enable"] = true,
},
["width"] = 82,
["health"] = {
["position"] = "BOTTOMLEFT",
["text_format"] = "",
},
},
["player"] = {
["debuffs"] = {
["sizeOverride"] = 30,
["enable"] = false,
["anchorPoint"] = "TOPRIGHT",
["priority"] = "Blacklist,Personal,nonPersonal,MyDebuffsBL,MyDebuffsWL",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 5,
},
["classbar"] = {
["enable"] = false,
},
["customTexts"] = {
["HP"] = {
["attachTextTo"] = "Health",
["xOffset"] = -3,
["text_format"] = "[health:percent] I [health:current:shortvalue]",
["yOffset"] = -25,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "RIGHT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 14,
},
["Absorb"] = {
["attachTextTo"] = "Health",
["xOffset"] = -3,
["text_format"] = "[absorbs]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "RIGHT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 14,
},
},
["healPrediction"] = {
["absorbStyle"] = "WRAPPED",
},
["height"] = 30,
["buffs"] = {
["sizeOverride"] = 34,
["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,blockNoDuration,nonPersonal,MyBuffsWL,MyBuffsBL",
["countFont"] = "ITCAvantGardeGothicDemi",
},
["raidicon"] = {
["enable"] = false,
},
["pvp"] = {
["text_format"] = " ||cFFB04F4F[pvptimer][mouseover]||r",
},
["aurabar"] = {
["enable"] = false,
["attachTo"] = "FRAME",
},
["castbar"] = {
["hidetext"] = true,
["icon"] = false,
["insideInfoPanel"] = false,
["width"] = 312,
["height"] = 8,
},
["width"] = 250,
["CombatIcon"] = {
["enable"] = false,
},
["health"] = {
["text_format"] = "",
["yOffset"] = -10,
},
["raidRoleIcons"] = {
["enable"] = false,
},
["power"] = {
["enable"] = false,
["yOffset"] = -8,
["strataAndLevel"] = {
["frameLevel"] = 2,
},
},
},
["raid1"] = {
["pvpclassificationindicator"] = {
["enable"] = false,
},
["numGroups"] = 4,
["growthDirection"] = "RIGHT_UP",
["readycheckIcon"] = {
["position"] = "CENTER",
["size"] = 18,
},
["groupSpacing"] = 3,
["classbar"] = {
["height"] = 5,
["altPowerTextFormat"] = " ",
},
["customTexts"] = {
["RaidNameStatus"] = {
["attachTextTo"] = "Health",
["enable"] = true,
["text_format"] = "[status]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["xOffset"] = 0,
["size"] = 12,
},
["RaidName"] = {
["attachTextTo"] = "Health",
["enable"] = true,
["text_format"] = "[name:veryshort]",
["yOffset"] = 20,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "NONE",
["xOffset"] = 13,
["size"] = 11,
},
},
["healPrediction"] = {
["enable"] = true,
["absorbStyle"] = "WRAPPED",
},
["name"] = {
["position"] = "LEFT",
["xOffset"] = 9,
["text_format"] = "",
["yOffset"] = 20,
},
["height"] = 45,
["buffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 23,
["xOffset"] = -36,
["anchorPoint"] = "RIGHT",
["clickThrough"] = true,
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,TurtleBuffs",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 1,
["enable"] = true,
},
["raidicon"] = {
["attachTo"] = "TOPLEFT",
["yOffset"] = 6,
["xOffset"] = 60,
["size"] = 15,
},
["rdebuffs"] = {
["fontSize"] = 12,
["xOffset"] = -12,
["duration"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
},
["yOffset"] = 12,
["font"] = "ITCAvantGardeGothicDemi",
["stack"] = {
["color"] = {
["g"] = 1,
["b"] = 1,
},
["yOffset"] = 1,
},
},
["resurrectIcon"] = {
["attachTo"] = "RIGHT",
["xOffset"] = -5,
},
["debuffs"] = {
["countFontSize"] = 17,
["sizeOverride"] = 45,
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Boss,RaidDebuffs,CCDebuffs,Dispellable,Whitelist",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 4,
},
["roleIcon"] = {
["yOffset"] = 0,
["position"] = "TOPLEFT",
["xOffset"] = 0,
},
["width"] = 82,
["health"] = {
["position"] = "BOTTOMLEFT",
["text_format"] = "",
},
},
["targettarget"] = {
["debuffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 20,
["enable"] = false,
["anchorPoint"] = "TOPRIGHT",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 4,
},
["power"] = {
["enable"] = false,
["height"] = 5,
},
["customTexts"] = {
["TargetName"] = {
["attachTextTo"] = "Health",
["xOffset"] = 0,
["text_format"] = "[name:short]",
["yOffset"] = 15,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 13,
},
},
["width"] = 100,
["height"] = 17,
["buffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["name"] = {
["position"] = "TOPRIGHT",
["text_format"] = "",
},
["raidicon"] = {
["enable"] = false,
},
},
["pettarget"] = {
["debuffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
["buffs"] = {
["countFont"] = "ITCAvantGardeGothicDemi",
},
},
["arena"] = {
["enable"] = false,
["customTexts"] = {
["ArenaNameStatus"] = {
["attachTextTo"] = "Health",
["xOffset"] = 0,
["text_format"] = "[status]",
["yOffset"] = 0,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "CENTER",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 12,
},
},
},
["assist"] = {
["enable"] = false,
},
["boss"] = {
["debuffs"] = {
["sizeOverride"] = 30,
["yOffset"] = -2,
["anchorPoint"] = "RIGHT",
["priority"] = "MyDebuffsWL,MyDebuffsBL,Blacklist,Blacklist All Classes,Boss,Personal,RaidDebuffs,CastByUnit,Whitelist",
["countFont"] = "ITCAvantGardeGothicDemi",
["perrow"] = 5,
},
["growthDirection"] = "UP",
["spacing"] = 37,
["buffIndicator"] = {
["enable"] = false,
},
["threatStyle"] = "GLOW",
["castbar"] = {
["enable"] = false,
["width"] = 150,
["height"] = 14,
},
["customTexts"] = {
["BossName"] = {
["attachTextTo"] = "Health",
["xOffset"] = -5,
["text_format"] = "[name:short]",
["yOffset"] = 12,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "RIGHT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 13,
},
["HP"] = {
["attachTextTo"] = "Frame",
["xOffset"] = 0,
["text_format"] = "[health:current:shortvalue] || [health:percent] ",
["yOffset"] = -22,
["font"] = "ITCAvantGardeGothicDemi",
["justifyH"] = "LEFT",
["fontOutline"] = "NONE",
["enable"] = true,
["size"] = 12,
},
},
["width"] = 150,
["name"] = {
["text_format"] = "",
},
["power"] = {
["xOffset"] = 0,
["yOffset"] = -14,
["attachTextTo"] = "Frame",
["position"] = "BOTTOMRIGHT",
["height"] = 6,
},
["height"] = 30,
["buffs"] = {
["countFontSize"] = 11,
["sizeOverride"] = 20,
["yOffset"] = 0,
["anchorPoint"] = "TOPLEFT",
["priority"] = "MyBuffsWL,MyBuffsBL,Blacklist,CastByUnit,Dispellable,Whitelist,RaidBuffsElvUI",
["countFont"] = "ITCAvantGardeGothicDemi",
},
["health"] = {
["xOffset"] = 0,
["text_format"] = "",
},
["raidicon"] = {
["attachTo"] = "LEFT",
["enable"] = false,
["xOffset"] = 5,
["yOffset"] = 3,
},
},
},
["font"] = "ITCAvantGardeGothicDemi",
["colors"] = {
["healthclass"] = true,
["customhealthbackdrop"] = true,
["healPrediction"] = {
["absorbs"] = {
["a"] = 0.5,
},
["overabsorbs"] = {
["a"] = 0.5,
},
},
["auraBarBuff"] = {
["b"] = 0.73,
["g"] = 0.55,
["r"] = 0.96,
},
["disconnected"] = {
["b"] = 0.32941176470588,
["g"] = 0.32941176470588,
["r"] = 0.32941176470588,
},
["selection"] = {
[3] = {
["b"] = 0.29411764705882,
["g"] = 0.68627450980392,
["r"] = 0.29411764705882,
},
},
["colorhealthbyvalue"] = false,
["health_backdrop"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["castClassColor"] = true,
["health_backdrop_dead"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["debuffHighlight"] = {
["Disease"] = {
["a"] = 0.80037917196751,
},
["Curse"] = {
["a"] = 0.80917340517044,
},
["Magic"] = {
["a"] = 0.80917340517044,
},
["Poison"] = {
["a"] = 0.80037917196751,
},
},
["frameGlow"] = {
["mainGlow"] = {
["class"] = true,
},
["mouseoverGlow"] = {
["color"] = {
["a"] = 0.50671881437302,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["enable"] = false,
},
},
["health"] = {
["b"] = 0.30196078431373,
["g"] = 0.054901960784314,
["r"] = 0.30980392156863,
},
["useDeadBackdrop"] = true,
["reaction"] = {
["BAD"] = {
["r"] = 0.7843137254902,
},
["NEUTRAL"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.7843137254902,
},
["GOOD"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.25098039215686,
},
},
},
["fontOutline"] = "NONE",
["statusbar"] = "Melli Dark",
["cooldown"] = {
["fonts"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
},
["threshold"] = 5,
},
},
["datatexts"] = {
["font"] = "ITCAvantGardeGothicDemi",
["fontSize"] = 11,
["panels"] = {
["LeftMiniPanel"] = "Time",
["MinimapPanel"] = {
"Time",
["1"] = "Time",
["3"] = "Combat",
["2"] = "Time",
["5"] = "Time",
["4"] = "Time",
["border"] = false,
["6"] = "Time",
["panelTransparency"] = true,
},
["RightChatDataPanel"] = {
["middle"] = "",
["panelTransparency"] = true,
["enable"] = false,
["border"] = false,
},
["LeftChatDataPanel"] = {
[3] = "System",
["3"] = "System",
["2"] = "",
["panelTransparency"] = true,
["right"] = "System",
["7"] = "System",
["6"] = "System",
["9"] = "System",
["8"] = "System",
["border"] = false,
["5"] = "System",
["4"] = "",
},
},
["noCombatHover"] = true,
},
["actionbar"] = {
["bar3"] = {
["hotkeyFontOutline"] = "OUTLINE",
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["visibility"] = "",
["countFontSize"] = 11,
["macroFontSize"] = 11,
["professionQuality"] = {
["scale"] = 0.35,
},
["countFont"] = "ITCAvantGardeGothicDemi",
["buttons"] = 12,
["countFontOutline"] = "OUTLINE",
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["buttonsPerRow"] = 12,
},
["bar8"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["countFontSize"] = 11,
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["professionQuality"] = {
["scale"] = 0.35,
},
["hotkeyFontOutline"] = "OUTLINE",
},
["desaturateOnCooldown"] = true,
["fontOutline"] = "OUTLINE",
["bar9"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["countFontSize"] = 11,
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["professionQuality"] = {
["scale"] = 0.35,
},
["hotkeyFontOutline"] = "OUTLINE",
},
["bar1"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["macroTextPosition"] = "BOTTOM",
["hotkeyFontSize"] = 11,
["visibility"] = "show;[petbattle] hide; [vehicleui][overridebar][possessbar] show; hide",
["countFontSize"] = 11,
["professionQuality"] = {
["scale"] = 0.35,
},
["macroFontOutline"] = "OUTLINE",
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["macroTextXOffset"] = -5,
["hotkeyFontOutline"] = "SHADOWOUTLINE",
["paging"] = {
["DRUID"] = "",
},
["macroTextYOffset"] = 0,
},
["font"] = "ITCAvantGardeGothicDemi",
["bar7"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["countFontSize"] = 11,
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["professionQuality"] = {
["scale"] = 0.35,
},
["hotkeyFontOutline"] = "OUTLINE",
["paging"] = {
["DRUID"] = "",
},
},
["bar15"] = {
["professionQuality"] = {
["scale"] = 0.35,
},
},
["bar13"] = {
["professionQuality"] = {
["scale"] = 0.35,
},
["buttons"] = 8,
["mouseover"] = true,
},
["barPet"] = {
["hotkeyFontOutline"] = "OUTLINE",
["hotkeyFontSize"] = 11,
["countFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["buttonSize"] = 24,
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["buttonsPerRow"] = 10,
},
["bar6"] = {
["enabled"] = true,
["macroFont"] = "ITCAvantGardeGothicDemi",
["buttonsPerRow"] = 1,
["countFontSize"] = 11,
["hotkeyFontOutline"] = "SHADOW",
["professionQuality"] = {
["scale"] = 0.35,
},
["buttonSpacing"] = 1,
["countFont"] = "ITCAvantGardeGothicDemi",
["buttonSize"] = 34,
["countFontOutline"] = "SHADOWOUTLINE",
["macroFontSize"] = 11,
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["buttons"] = 6,
},
["bar10"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["countFontSize"] = 11,
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["professionQuality"] = {
["scale"] = 0.35,
},
["hotkeyFontOutline"] = "OUTLINE",
},
["vehicleExitButton"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
},
["microbar"] = {
["buttons"] = 11,
},
["bar2"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["enabled"] = true,
["macroFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
["visibility"] = "",
["countFontSize"] = 11,
["professionQuality"] = {
["scale"] = 0.35,
},
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["macroFontSize"] = 11,
["hotkeyFontOutline"] = "OUTLINE",
},
["bar14"] = {
["professionQuality"] = {
["scale"] = 0.35,
},
},
["bar5"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["macroFont"] = "ITCAvantGardeGothicDemi",
["buttonsPerRow"] = 12,
["visibility"] = "",
["countFontSize"] = 11,
["professionQuality"] = {
["scale"] = 0.35,
},
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["buttons"] = 12,
["countFontOutline"] = "OUTLINE",
["hotkeyFontOutline"] = "OUTLINE",
["hotkeyFontSize"] = 11,
},
["fontSize"] = 11,
["extraActionButton"] = {
["hotkeyFontOutline"] = "OUTLINE",
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["hotkeyFontSize"] = 11,
},
["stanceBar"] = {
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["enabled"] = false,
["hotkeyFontSize"] = 11,
["hotkeyFontOutline"] = "OUTLINE",
},
["cooldown"] = {
["fonts"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
["fontOutline"] = "SHADOWOUTLINE",
},
},
["bar4"] = {
["macroFont"] = "ITCAvantGardeGothicDemi",
["backdrop"] = false,
["hotkeyFontSize"] = 11,
["visibility"] = "",
["countFontSize"] = 11,
["point"] = "BOTTOMLEFT",
["macroFontSize"] = 11,
["countFont"] = "ITCAvantGardeGothicDemi",
["countFontOutline"] = "OUTLINE",
["professionQuality"] = {
["scale"] = 0.35,
},
["hotkeyFontOutline"] = "OUTLINE",
["hotkeyFont"] = "ITCAvantGardeGothicDemi",
["buttonsPerRow"] = 12,
},
},
["nameplates"] = {
["plateSize"] = {
["personalWidth"] = 50,
["friendlyWidth"] = 50,
["enemyHeight"] = 10,
["friendlyHeight"] = 10,
["enemyWidth"] = 50,
["personalHeight"] = 10,
},
["smoothbars"] = true,
["clickThrough"] = {
["personal"] = true,
["friendly"] = true,
},
["overlapV"] = 1.5,
["filters"] = {
["Shadow"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ ML Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Necrotic Wake"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ AD Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["Tank Aggro Bad"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Mists of Tirna Scithe"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Sanguine Depths"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ SoB Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ SotS Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["ElvUI_Target"] = {
["triggers"] = {
["enable"] = false,
},
},
["M+ UR Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Theater of Pain"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ OM Lower Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ ToS Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ KR Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ WM Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["Balance"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Plaguefall"] = {
["triggers"] = {
["enable"] = true,
},
},
["AssasinGarroteAndRupture"] = {
["triggers"] = {
["enable"] = true,
},
},
["Aggro Bad"] = {
["triggers"] = {
["enable"] = true,
},
},
["Affliction"] = {
["triggers"] = {
["enable"] = true,
},
},
["ElvUI_NonTarget"] = {
["triggers"] = {
["enable"] = false,
},
},
["M+ De Other Side"] = {
["triggers"] = {
["enable"] = true,
},
},
["WW monk"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ OM Upper Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["Tank Aggro Bad Transition"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ TD Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["Destruction"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ FH Interrupts"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Spires of Ascension"] = {
["triggers"] = {
["enable"] = true,
},
},
["AssasinRupture"] = {
["triggers"] = {
["enable"] = true,
},
},
["M+ Halls of Atonement"] = {
["triggers"] = {
["enable"] = true,
},
},
["Aggro Bad Transition"] = {
["triggers"] = {
["enable"] = true,
},
},
},
["threat"] = {
["enable"] = false,
},
["bossMods"] = {
["enable"] = false,
},
["units"] = {
["ENEMY_NPC"] = {
["debuffs"] = {
["countFontSize"] = 11,
["yOffset"] = -5,
["priority"] = "Blacklist,Blacklist All Classes,Personal,CCDebuffs",
["size"] = 25,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 6,
},
["portrait"] = {
["height"] = 16,
["xOffset"] = 0,
["width"] = 16,
["yOffset"] = 0,
},
["enable"] = false,
["raidTargetIndicator"] = {
["xOffset"] = -2,
["size"] = 32,
},
["eliteIcon"] = {
["position"] = "TOPLEFT",
["xOffset"] = 0,
["yOffset"] = -16,
},
["level"] = {
["enable"] = false,
["format"] = "[distance][level][shortclassification]",
},
["power"] = {
["text"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
},
["pvpindicator"] = {
["showBadge"] = false,
},
["health"] = {
["height"] = 16,
["text"] = {
["fontSize"] = 12,
["xOffset"] = 60,
["yOffset"] = -8,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[perhp]%",
},
},
["castbar"] = {
["fontSize"] = 12,
["sourceInterrupt"] = false,
["yOffset"] = -14,
["iconSize"] = 29,
["castTimeFormat"] = "REMAINING",
["iconOffsetY"] = -1,
["font"] = "ITCAvantGardeGothicDemi",
["height"] = 10,
},
["questIcon"] = {
["fontSize"] = 10,
["font"] = "ITCAvantGardeGothicDemi",
},
["buffs"] = {
["countFontSize"] = 11,
["yOffset"] = -5,
["size"] = 30,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 1,
},
["name"] = {
["parent"] = "Health",
["yOffset"] = -5,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[name:short]",
},
},
["FRIENDLY_NPC"] = {
["debuffs"] = {
["yOffset"] = -5,
["priority"] = "Blacklist,Blacklist All Classes,Personal,CCDebuffs",
["size"] = 25,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 6,
},
["portrait"] = {
["height"] = 16,
["xOffset"] = 0,
["width"] = 16,
["yOffset"] = 0,
},
["raidTargetIndicator"] = {
["xOffset"] = -2,
["size"] = 32,
},
["eliteIcon"] = {
["position"] = "TOPLEFT",
["xOffset"] = 0,
["yOffset"] = -16,
},
["level"] = {
["enable"] = false,
["format"] = "[level][shortclassification]",
},
["castbar"] = {
["fontSize"] = 12,
["sourceInterrupt"] = false,
["yOffset"] = -14,
["iconSize"] = 29,
["castTimeFormat"] = "REMAINING",
["iconOffsetY"] = -1,
["font"] = "ITCAvantGardeGothicDemi",
["height"] = 10,
},
["questIcon"] = {
["fontSize"] = 10,
["font"] = "ITCAvantGardeGothicDemi",
},
["pvpindicator"] = {
["showBadge"] = false,
},
["health"] = {
["height"] = 16,
["text"] = {
["fontSize"] = 12,
["xOffset"] = 60,
["yOffset"] = -8,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[perhp]%",
},
},
["power"] = {
["text"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
},
["nameOnly"] = false,
["buffs"] = {
["yOffset"] = -5,
["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
["size"] = 30,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 1,
},
["name"] = {
["parent"] = "Health",
["yOffset"] = -4,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[name:short]",
},
},
["ENEMY_PLAYER"] = {
["debuffs"] = {
["countFontSize"] = 11,
["yOffset"] = -5,
["countPosition"] = "TOP",
["priority"] = "Blacklist,Blacklist All Classes,Personal,CCDebuffs",
["size"] = 25,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 6,
},
["portrait"] = {
["height"] = 16,
["xOffset"] = 0,
["width"] = 16,
["yOffset"] = 0,
},
["enable"] = false,
["raidTargetIndicator"] = {
["xOffset"] = -2,
["size"] = 32,
},
["level"] = {
["enable"] = false,
["format"] = "[distance][level][shortclassification]",
},
["power"] = {
["text"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
},
["pvpindicator"] = {
["showBadge"] = false,
},
["title"] = {
["format"] = "[npctitle]",
},
["castbar"] = {
["fontSize"] = 12,
["sourceInterrupt"] = false,
["yOffset"] = -14,
["iconSize"] = 29,
["castTimeFormat"] = "REMAINING",
["iconOffsetY"] = -1,
["font"] = "ITCAvantGardeGothicDemi",
["height"] = 10,
},
["buffs"] = {
["countFontSize"] = 11,
["yOffset"] = -5,
["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
["size"] = 30,
["countFont"] = "ITCAvantGardeGothicDemi",
["maxDuration"] = 0,
["numAuras"] = 1,
},
["health"] = {
["height"] = 16,
["text"] = {
["fontSize"] = 12,
["xOffset"] = 60,
["yOffset"] = -8,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[perhp]%",
},
},
["name"] = {
["parent"] = "Health",
["yOffset"] = -5,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[name:short]",
},
},
["FRIENDLY_PLAYER"] = {
["debuffs"] = {
["enable"] = false,
["yOffset"] = -5,
["priority"] = "Blacklist,Blacklist All Classes,Personal,CCDebuffs",
["size"] = 25,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 6,
},
["portrait"] = {
["height"] = 16,
["xOffset"] = 0,
["width"] = 16,
["yOffset"] = 0,
},
["raidTargetIndicator"] = {
["xOffset"] = -2,
["enable"] = false,
["size"] = 32,
},
["level"] = {
["enable"] = false,
["format"] = "[level][shortclassification]",
},
["castbar"] = {
["fontSize"] = 12,
["enable"] = false,
["sourceInterrupt"] = false,
["yOffset"] = -14,
["iconSize"] = 29,
["castTimeFormat"] = "REMAINING",
["iconOffsetY"] = -1,
["font"] = "ITCAvantGardeGothicDemi",
["height"] = 10,
},
["showTitle"] = false,
["pvpindicator"] = {
["showBadge"] = false,
},
["power"] = {
["text"] = {
["font"] = "ITCAvantGardeGothicDemi",
},
},
["health"] = {
["height"] = 16,
["text"] = {
["fontSize"] = 12,
["xOffset"] = 60,
["yOffset"] = -8,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[perhp]%",
},
},
["nameOnly"] = true,
["name"] = {
["enable"] = false,
["yOffset"] = -4,
["font"] = "ITCAvantGardeGothicDemi",
["format"] = "[name:short]",
["parent"] = "Health",
},
["buffs"] = {
["enable"] = false,
["yOffset"] = -5,
["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
["size"] = 30,
["countFont"] = "ITCAvantGardeGothicDemi",
["numAuras"] = 1,
},
["title"] = {
["format"] = "[npctitle]",
},
["markHealers"] = false,
},
},
["statusbar"] = "Melli Dark",
["clampToScreen"] = true,
["colors"] = {
["castNoInterruptColor"] = {
["b"] = 0.25098039215686,
["g"] = 0.25098039215686,
["r"] = 0.7843137254902,
},
["threat"] = {
["goodTransition"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.7843137254902,
},
["goodColor"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.25098039215686,
},
["offTankColor"] = {
["b"] = 0.7843137254902,
["g"] = 0.25098039215686,
["r"] = 0.7843137254902,
},
["badTransition"] = {
["b"] = 0,
["g"] = 0.3921568627451,
["r"] = 0.7843137254902,
},
["badColor"] = {
["b"] = 0.25098039215686,
["g"] = 0.25098039215686,
["r"] = 0.7843137254902,
},
},
["castColor"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.7843137254902,
},
["reactions"] = {
["good"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.25098039215686,
},
["bad"] = {
["b"] = 0.25098039215686,
["g"] = 0.25098039215686,
["r"] = 0.7843137254902,
},
["neutral"] = {
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.7843137254902,
},
},
["castbarDesaturate"] = false,
["selection"] = {
{
["b"] = 0,
["g"] = 0.3921568627451,
["r"] = 0.7843137254902,
},
{
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.7843137254902,
},
{
["b"] = 0.25098039215686,
["g"] = 0.7843137254902,
["r"] = 0.25098039215686,
},
},
},
["fadeIn"] = false,
["visibility"] = {
["enemy"] = {
["guardians"] = true,
},
},
["cooldown"] = {
["fonts"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
["fontSize"] = 20,
["fontOutline"] = "SHADOWOUTLINE",
},
["threshold"] = 5,
},
["font"] = "ITCAvantGardeGothicDemi",
},
["cooldown"] = {
["secondsColor"] = {
["b"] = 1,
},
["fonts"] = {
["enable"] = true,
["font"] = "ITCAvantGardeGothicDemi",
["fontSize"] = 12,
["fontOutline"] = "SHADOWOUTLINE",
},
["threshold"] = 5,
},
["chat"] = {
["tabFontOutline"] = "SHADOWOUTLINE",
["numScrollMessages"] = 1,
["panelHeightRight"] = 182,
["font"] = "ITCAvantGardeGothicDemi",
["panelWidth"] = 417,
["panelHeight"] = 183,
["panelWidthRight"] = 329,
["panelBackdrop"] = "LEFT",
["fontOutline"] = "SHADOWOUTLINE",
["separateSizes"] = true,
["panelSnapLeftID"] = 1,
["fontSize"] = 11,
["tabFontSize"] = 11,
["fade"] = false,
["tabFont"] = "ITCAvantGardeGothicDemi",
["historySize"] = 500,
["tabSelector"] = "NONE",
},
},
},
["gold"] = {
["Ревущий фьорд"] = {
["Бимладен"] = 5962310169,
},
["Свежеватель Душ"] = {
["Вольтчара"] = 63548,
},
},
["global"] = {
["unitframe"] = {
["aurafilters"] = {
["Blacklist"] = {
["spells"] = {
[355462] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[186401] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
},
["RaidDebuffs"] = {
["spells"] = {
[347807] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[334909] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
},
["MyDebuffsBL"] = {
["spells"] = {
[357610] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[199368] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
["type"] = "Blacklist",
},
["MyBuffsBL"] = {
["spells"] = {
[225788] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[206150] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[355794] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
["type"] = "Blacklist",
},
["MyDebuffsWL"] = {
["spells"] = {
[397210] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[351119] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[371966] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[324154] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[414552] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[350101] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[344874] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[356923] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[331997] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[330532] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[423416] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[414300] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[328494] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[164632] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[163740] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227777] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[356548] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[320147] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[403724] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[336277] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[278456] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227524] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[321807] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[332836] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[357827] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[352345] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[418200] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[418009] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[319898] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[333477] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[319070] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[347949] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[228993] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[333861] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[334053] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[340556] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[99692] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[173149] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[299438] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[299502] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[392641] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[250096] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[319521] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[429363] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[176147] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[99693] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[321755] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[178156] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[333231] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227977] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[327814] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[233620] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[407120] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[328453] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[425417] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[412285] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[407313] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[374037] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[319531] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[301299] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[355487] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[16856] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[391762] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[176025] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[414585] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[228524] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[410953] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[349627] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[350010] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[164648] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[374300] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[374295] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227965] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[274555] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227473] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[328593] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[409492] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[385331] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[436841] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[419629] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[331399] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[347807] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[338731] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[320180] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[412044] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[409558] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[436652] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[166340] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[404650] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[354334] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[228013] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[318587] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[293724] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[300675] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[362194] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[413547] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[342961] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[413131] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[375416] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[366849] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[320200] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[320631] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[372141] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[323437] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[328664] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[257478] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[326242] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[407906] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[407715] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[327646] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[416258] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[176033] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[293986] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[384575] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[357281] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[331415] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[338357] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227480] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[419351] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[298259] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[395292] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[414922] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[29667] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[330135] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[327649] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[340208] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[160703] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[232135] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[426590] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[324652] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[88194] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[167038] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[324444] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[408805] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[299474] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[256106] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[415436] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[324146] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[333708] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[373744] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[173113] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[373872] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[164837] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[412505] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[327882] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[324148] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[355832] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[326826] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[163447] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[346844] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[349954] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[356407] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227325] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[371070] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[229250] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[297904] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[228241] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[300436] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[323195] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[173489] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[227985] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[328501] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[334926] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[27638] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
["type"] = "Whitelist",
},
["MyBuffsWL"] = {
["spells"] = {
[328737] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[429271] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[193065] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[391171] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[586] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[335161] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
[291937] = {
["enable"] = true,
["priority"] = 0,
["stackThreshold"] = 0,
},
},
["type"] = "Whitelist",
},
},
["aurawatch"] = {
["PALADIN"] = {
[1044] = {
["point"] = "BOTTOM",
["yOffset"] = -1,
},
[200025] = {
["xOffset"] = 1,
["yOffset"] = 1,
["sizeOffset"] = 4,
["color"] = {
["b"] = 0,
["g"] = 0.4784313725490196,
["r"] = 1,
},
},
[287280] = {
["sizeOffset"] = 4,
["point"] = "TOPRIGHT",
["xOffset"] = 1,
["color"] = {
["b"] = 0,
["g"] = 0.4588235294117647,
["r"] = 1,
},
["yOffset"] = 1,
},
[6940] = {
["xOffset"] = 1,
["yOffset"] = -1,
["sizeOffset"] = 4,
},
[223306] = {
["xOffset"] = -1,
["yOffset"] = -1,
["sizeOffset"] = 4,
["color"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
[1022] = {
["point"] = "RIGHT",
["xOffset"] = 1,
["enabled"] = false,
["sizeOffset"] = 4,
},
[53563] = {
["point"] = "TOPLEFT",
["xOffset"] = -1,
["yOffset"] = 1,
["color"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
[204018] = {
["point"] = "RIGHT",
["sizeOffset"] = 4,
["xOffset"] = 1,
},
[156910] = {
["point"] = "TOPLEFT",
["xOffset"] = -1,
["yOffset"] = 1,
["color"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
},
["PRIEST"] = {
[139] = {
["point"] = "TOPRIGHT",
["color"] = {
["a"] = 1,
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
["yOffset"] = 1,
["sizeOffset"] = 4,
["xOffset"] = -12,
},
[193065] = {
["xOffset"] = 1,
["yOffset"] = -1,
["sizeOffset"] = 4,
},
[10060] = {
["enabled"] = false,
},
[214206] = {
["xOffset"] = 1,
["yOffset"] = 1,
["sizeOffset"] = 4,
},
[17] = {
["point"] = "TOPRIGHT",
["color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 0,
["r"] = 1,
},
["yOffset"] = 1,
["enabled"] = false,
["sizeOffset"] = 4,
["xOffset"] = -12,
},
[33206] = {
["enabled"] = false,
},
[194384] = {
["xOffset"] = 1,
["yOffset"] = 1,
["sizeOffset"] = 4,
},
[47788] = {
["enabled"] = false,
},
[6788] = {
["point"] = "RIGHT",
["xOffset"] = 0,
["sizeOffset"] = 4,
["color"] = {
["a"] = 1,
},
},
[41635] = {
["point"] = "TOPRIGHT",
["color"] = {
["a"] = 1,
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
["yOffset"] = 1,
["sizeOffset"] = 4,
["xOffset"] = 1,
},
},
["DRUID"] = {
[207386] = {
["enabled"] = false,
},
[188550] = {
["point"] = "RIGHT",
["yOffset"] = -8,
["sizeOffset"] = 4,
["color"] = {
["a"] = 1,
["b"] = 0.1960784494876862,
["g"] = 0.7843137979507446,
["r"] = 0.7843137979507446,
},
},
[157982] = {
["enabled"] = false,
},
[203554] = {
["point"] = "TOPRIGHT",
["color"] = {
["a"] = 1,
},
["yOffset"] = 14,
["enabled"] = false,
["sizeOffset"] = 4,
["xOffset"] = -12,
},
[155777] = {
["xOffset"] = -13,
["yOffset"] = -8,
["sizeOffset"] = 4,
},
[774] = {
["point"] = "BOTTOMRIGHT",
["xOffset"] = -13,
["sizeOffset"] = 4,
["color"] = {
["a"] = 1,
},
},
[102351] = {
["point"] = "RIGHT",
["xOffset"] = 1,
["enabled"] = false,
["sizeOffset"] = 4,
},
[102352] = {
["point"] = "RIGHT",
["xOffset"] = 1,
["enabled"] = false,
["sizeOffset"] = 4,
},
[391891] = {
["point"] = "BOTTOMLEFT",
["yOffset"] = -1,
["enabled"] = false,
["countY"] = 0,
["textThreshold"] = 60,
["countAnchor"] = "RIGHT",
["sizeOffset"] = 3,
["countX"] = 15,
["xOffset"] = -1,
},
[33763] = {
["point"] = "RIGHT",
["yOffset"] = -8,
["sizeOffset"] = 4,
["color"] = {
["a"] = 1,
["b"] = 0.1960784494876862,
["g"] = 0.7843137979507446,
["r"] = 0.7843137979507446,
},
},
[8936] = {
["point"] = "BOTTOMRIGHT",
["sizeOffset"] = 4,
},
[200389] = {
["xOffset"] = 0,
["yOffset"] = -1,
["enabled"] = false,
["sizeOffset"] = 4,
},
[48438] = {
["xOffset"] = -26,
["sizeOffset"] = 4,
["color"] = {
["a"] = 1,
["g"] = 0.4000000357627869,
["r"] = 0.8000000715255737,
},
},
},
["MONK"] = {
[325209] = {
["enabled"] = false,
},
[115175] = {
["point"] = "RIGHT",
["sizeOffset"] = 4,
["xOffset"] = 1,
},
[191840] = {
["xOffset"] = 1,
["yOffset"] = -1,
["sizeOffset"] = 4,
},
[116849] = {
["enabled"] = false,
},
[119611] = {
["point"] = "TOPRIGHT",
["xOffset"] = 1,
["yOffset"] = 1,
["sizeOffset"] = 4,
},
[124682] = {
["point"] = "TOPRIGHT",
["xOffset"] = -12,
["yOffset"] = 1,
["sizeOffset"] = 4,
},
[116841] = {
["enabled"] = false,
},
},
["SHAMAN"] = {
[974] = {
["xOffset"] = 1,
["yOffset"] = -1,
["sizeOffset"] = 4,
},
[61295] = {
["xOffset"] = 1,
["yOffset"] = 1,
["sizeOffset"] = 4,
},
},
},
},
["general"] = {
["mapAlphaWhenMoving"] = 0.7000000000000001,
["UIScale"] = 0.7000000000000001,
},
["datatexts"] = {
["settings"] = {
["Currencies"] = {
["tooltipData"] = {
[13] = {
nil,
nil,
nil,
true,
},
[17] = {
nil,
nil,
nil,
true,
},
[21] = {
nil,
nil,
nil,
true,
},
[22] = {
nil,
nil,
nil,
true,
},
[34] = {
nil,
nil,
nil,
true,
},
[44] = {
nil,
nil,
nil,
true,
},
[53] = {
nil,
nil,
nil,
true,
},
[56] = {
nil,
nil,
nil,
true,
},
},
},
},
},
["nameplates"] = {
["filters"] = {
["ElvUI_NonTarget"] = {
["actions"] = {
["glow"] = {
["speed"] = 0.3,
["lines"] = 8,
["frameLevel"] = 5,
["useColor"] = true,
["enable"] = false,
["style"] = "Pixel Glow",
["color"] = {
0.09,
0.52,
0.82,
0.9,
},
["size"] = 1,
},
["tags"] = {
["name"] = "",
["power"] = "",
["level"] = "",
["health"] = "",
["title"] = "",
},
["color"] = {
["healthClass"] = false,
["power"] = false,
["healthColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["border"] = false,
["health"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderClass"] = false,
["powerClass"] = false,
["powerColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["nameOnly"] = false,
["flash"] = {
["enable"] = false,
["class"] = false,
["speed"] = 4,
["color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["hide"] = false,
["usePortrait"] = false,
["scale"] = 1,
["texture"] = {
["enable"] = false,
["texture"] = "ElvUI Norm",
},
},
["triggers"] = {
["known"] = {
["playerSpell"] = false,
["spells"] = {
},
["notKnown"] = false,
},
["class"] = {
},
["notInParty"] = false,
["notCharmed"] = false,
["role"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["isPossessed"] = false,
["notResting"] = false,
["level"] = false,
["isNotPet"] = false,
["threat"] = {
["good"] = false,
["offTankBadTransition"] = false,
["bad"] = false,
["offTank"] = false,
["enable"] = false,
["offTankGoodTransition"] = false,
["badTransition"] = false,
["goodTransition"] = false,
},
["overHealthThreshold"] = 0,
["playerCanAttack"] = false,
["items"] = {
},
["bossMods"] = {
["missingAuras"] = false,
["missingAura"] = false,
["hasAura"] = false,
["auras"] = {
},
},
["isConnected"] = false,
["creatureType"] = {
["Dragonkin"] = false,
["Humanoid"] = false,
["Elemental"] = false,
["Critter"] = false,
["enable"] = false,
["Gas Cloud"] = false,
["Totem"] = false,
["Non-combat Pet"] = false,
["Wild Pet"] = false,
["Demon"] = false,
["Not specified"] = false,
["Undead"] = false,
["Aberration"] = false,
["Giant"] = false,
["Beast"] = false,
["Mechanical"] = false,
},
["notInRaid"] = false,
["isBeingResurrected"] = false,
["isUnconscious"] = false,
["healthThreshold"] = false,
["unitRole"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["hasTitleNPC"] = false,
["keyMod"] = {
["Alt"] = false,
["LeftControl"] = false,
["RightShift"] = false,
["enable"] = false,
["RightAlt"] = false,
["LeftShift"] = false,
["Modifier"] = false,
["Shift"] = false,
["RightControl"] = false,
["LeftAlt"] = false,
["Control"] = false,
},
["noTitleNPC"] = false,
["healthUsePlayer"] = false,
["raidTarget"] = {
["circle"] = false,
["square"] = false,
["diamond"] = false,
["cross"] = false,
["star"] = false,
["triangle"] = false,
["skull"] = false,
["moon"] = false,
},
["isQuest"] = false,
["underPowerThreshold"] = 0,
["instanceDifficulty"] = {
["dungeon"] = {
["normal"] = false,
["mythic+"] = false,
["heroic"] = false,
["timewalking"] = false,
["mythic"] = false,
},
["raid"] = {
["normal"] = false,
["legacy25normal"] = false,
["heroic"] = false,
["legacy10normal"] = false,
["legacy10heroic"] = false,
["legacy25heroic"] = false,
["lfr"] = false,
["timewalking"] = false,
["mythic"] = false,
},
},
["minlevel"] = 0,
["notDeadOrGhost"] = false,
["overPowerThreshold"] = 0,
["notMyGuild"] = false,
["faction"] = {
["Horde"] = false,
["Alliance"] = false,
["Neutral"] = false,
},
["location"] = {
["zoneNamesEnabled"] = false,
["subZoneNamesEnabled"] = false,
["zoneNames"] = {
},
["mapIDs"] = {
},
["subZoneNames"] = {
},
["instanceIDs"] = {
},
["mapIDEnabled"] = false,
["instanceIDEnabled"] = false,
},
["isTapDenied"] = false,
["debuffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["fromPet"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromMe"] = false,
["hasNoDispellable"] = false,
["hasDispellable"] = false,
},
["instanceType"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = false,
["none"] = false,
},
["inCombatUnit"] = false,
["notOthersPet"] = false,
["amountBelow"] = 0,
["isCharmed"] = false,
["powerThreshold"] = false,
["inVehicle"] = false,
["amountAbove"] = 0,
["notQuest"] = false,
["underHealthThreshold"] = 0,
["nameplateType"] = {
["player"] = false,
},
["isOthersPet"] = false,
["maxlevel"] = 0,
["isConscious"] = false,
["isNotTapDenied"] = false,
["powerUsePlayer"] = false,
["notPossessed"] = false,
["outOfVehicleUnit"] = false,
["reactionType"] = {
["enabled"] = false,
["reputation"] = false,
["friendly"] = false,
["revered"] = false,
["honored"] = false,
["hostile"] = false,
["unfriendly"] = false,
["exalted"] = false,
["neutral"] = false,
["hated"] = false,
},
["outOfCombatUnit"] = false,
["buffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["hasNoStealable"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromPet"] = false,
["fromMe"] = false,
["hasStealable"] = false,
},
["isPvP"] = false,
["inCombat"] = false,
["isOwnedByPlayer"] = false,
["isNotPvP"] = false,
["isNotPlayerControlled"] = false,
["noTarget"] = false,
["names"] = {
},
["inParty"] = false,
["inPetBattle"] = false,
["curlevel"] = 0,
["isPlayerControlled"] = false,
["isTarget"] = false,
["inVehicleUnit"] = false,
["inMyGuild"] = false,
["inRaid"] = false,
["priority"] = 1,
["isPet"] = false,
["isResting"] = false,
["targetMe"] = false,
["classification"] = {
["elite"] = false,
["normal"] = false,
["trivial"] = false,
["minus"] = false,
["worldboss"] = false,
["rareelite"] = false,
["rare"] = false,
},
["notConnected"] = false,
["notTrivial"] = false,
["isTrivial"] = false,
["notBeingResurrected"] = false,
["notPetBattle"] = false,
["isNotOwnedByPlayer"] = false,
["isDeadOrGhost"] = false,
["questBoss"] = false,
["outOfVehicle"] = false,
["slots"] = {
},
["cooldowns"] = {
["mustHaveAll"] = false,
["names"] = {
},
},
["casting"] = {
["isChanneling"] = false,
["notSpell"] = false,
["isCasting"] = false,
["notChanneling"] = false,
["spells"] = {
},
["notCasting"] = false,
["interruptible"] = false,
},
["playerCanNotAttack"] = false,
["outOfCombat"] = false,
},
},
["ElvUI_Incorporeal"] = {
["actions"] = {
["glow"] = {
["speed"] = 0.3,
["lines"] = 8,
["frameLevel"] = 5,
["useColor"] = true,
["enable"] = false,
["style"] = "Pixel Glow",
["color"] = {
0.09,
0.52,
0.82,
0.9,
},
["size"] = 1,
},
["tags"] = {
["name"] = "",
["power"] = "",
["level"] = "",
["health"] = "",
["title"] = "",
},
["color"] = {
["healthClass"] = false,
["power"] = false,
["healthColor"] = {
["a"] = 1,
},
["border"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderClass"] = false,
["powerClass"] = false,
["powerColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["nameOnly"] = false,
["alpha"] = -1,
["flash"] = {
["enable"] = false,
["class"] = false,
["speed"] = 4,
["color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["hide"] = false,
["usePortrait"] = false,
["texture"] = {
["enable"] = false,
["texture"] = "ElvUI Norm",
},
},
["triggers"] = {
["known"] = {
["playerSpell"] = false,
["spells"] = {
},
["notKnown"] = false,
},
["class"] = {
},
["notInParty"] = false,
["notCharmed"] = false,
["role"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["isPossessed"] = false,
["notResting"] = false,
["level"] = false,
["isNotPet"] = false,
["threat"] = {
["good"] = false,
["offTankBadTransition"] = false,
["bad"] = false,
["offTank"] = false,
["enable"] = false,
["offTankGoodTransition"] = false,
["badTransition"] = false,
["goodTransition"] = false,
},
["overHealthThreshold"] = 0,
["playerCanAttack"] = false,
["items"] = {
},
["bossMods"] = {
["missingAuras"] = false,
["missingAura"] = false,
["hasAura"] = false,
["auras"] = {
},
},
["isConnected"] = false,
["creatureType"] = {
["Dragonkin"] = false,
["Humanoid"] = false,
["Elemental"] = false,
["Critter"] = false,
["enable"] = false,
["Gas Cloud"] = false,
["Totem"] = false,
["Non-combat Pet"] = false,
["Wild Pet"] = false,
["Demon"] = false,
["Not specified"] = false,
["Undead"] = false,
["Aberration"] = false,
["Giant"] = false,
["Beast"] = false,
["Mechanical"] = false,
},
["notInRaid"] = false,
["isBeingResurrected"] = false,
["requireTarget"] = false,
["isUnconscious"] = false,
["healthThreshold"] = false,
["unitRole"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["hasTitleNPC"] = false,
["keyMod"] = {
["Alt"] = false,
["LeftControl"] = false,
["RightShift"] = false,
["enable"] = false,
["RightAlt"] = false,
["LeftShift"] = false,
["Modifier"] = false,
["Shift"] = false,
["RightControl"] = false,
["LeftAlt"] = false,
["Control"] = false,
},
["noTitleNPC"] = false,
["healthUsePlayer"] = false,
["raidTarget"] = {
["circle"] = false,
["square"] = false,
["diamond"] = false,
["cross"] = false,
["star"] = false,
["triangle"] = false,
["skull"] = false,
["moon"] = false,
},
["isQuest"] = false,
["underPowerThreshold"] = 0,
["instanceDifficulty"] = {
["dungeon"] = {
["normal"] = false,
["mythic+"] = false,
["heroic"] = false,
["timewalking"] = false,
["mythic"] = false,
},
["raid"] = {
["normal"] = false,
["legacy25normal"] = false,
["heroic"] = false,
["legacy10normal"] = false,
["legacy10heroic"] = false,
["legacy25heroic"] = false,
["lfr"] = false,
["timewalking"] = false,
["mythic"] = false,
},
},
["minlevel"] = 0,
["notDeadOrGhost"] = false,
["overPowerThreshold"] = 0,
["notMyGuild"] = false,
["faction"] = {
["Horde"] = false,
["Alliance"] = false,
["Neutral"] = false,
},
["location"] = {
["zoneNamesEnabled"] = false,
["subZoneNamesEnabled"] = false,
["zoneNames"] = {
},
["mapIDs"] = {
},
["subZoneNames"] = {
},
["instanceIDs"] = {
},
["mapIDEnabled"] = false,
["instanceIDEnabled"] = false,
},
["isTapDenied"] = false,
["debuffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["fromPet"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromMe"] = false,
["hasNoDispellable"] = false,
["hasDispellable"] = false,
},
["instanceType"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = false,
["none"] = false,
},
["inCombatUnit"] = false,
["notOthersPet"] = false,
["amountBelow"] = 0,
["isCharmed"] = false,
["powerThreshold"] = false,
["inVehicle"] = false,
["inVehicleUnit"] = false,
["notQuest"] = false,
["notTarget"] = false,
["nameplateType"] = {
["player"] = false,
["friendlyPlayer"] = false,
["enemyPlayer"] = false,
["friendlyNPC"] = false,
},
["isOthersPet"] = false,
["isDeadOrGhost"] = false,
["isNotOwnedByPlayer"] = false,
["isNotTapDenied"] = false,
["powerUsePlayer"] = false,
["isOwnedByPlayer"] = false,
["outOfVehicleUnit"] = false,
["amountAbove"] = 0,
["outOfCombatUnit"] = false,
["buffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["hasNoStealable"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromPet"] = false,
["fromMe"] = false,
["hasStealable"] = false,
},
["isNotPlayerControlled"] = false,
["inCombat"] = false,
["notPossessed"] = false,
["isNotPvP"] = false,
["isPet"] = false,
["noTarget"] = false,
["reactionType"] = {
["enabled"] = false,
["reputation"] = false,
["friendly"] = false,
["revered"] = false,
["honored"] = false,
["hostile"] = false,
["unfriendly"] = false,
["exalted"] = false,
["neutral"] = false,
["hated"] = false,
},
["inParty"] = false,
["inPetBattle"] = false,
["curlevel"] = 0,
["isPlayerControlled"] = false,
["underHealthThreshold"] = 0,
["isTrivial"] = false,
["isTarget"] = false,
["slots"] = {
},
["inRaid"] = false,
["isResting"] = false,
["targetMe"] = false,
["classification"] = {
["elite"] = false,
["normal"] = false,
["trivial"] = false,
["minus"] = false,
["worldboss"] = false,
["rareelite"] = false,
["rare"] = false,
},
["notConnected"] = false,
["notTrivial"] = false,
["inMyGuild"] = false,
["notBeingResurrected"] = false,
["notPetBattle"] = false,
["outOfCombat"] = false,
["playerCanNotAttack"] = false,
["questBoss"] = false,
["outOfVehicle"] = false,
["isPvP"] = false,
["cooldowns"] = {
["mustHaveAll"] = false,
["names"] = {
},
},
["casting"] = {
["isChanneling"] = false,
["notSpell"] = false,
["isCasting"] = false,
["notChanneling"] = false,
["spells"] = {
},
["notCasting"] = false,
["interruptible"] = false,
},
["isConscious"] = false,
["maxlevel"] = 0,
},
},
["ElvUI_Target"] = {
["actions"] = {
["glow"] = {
["speed"] = 0.3,
["lines"] = 8,
["frameLevel"] = 5,
["useColor"] = true,
["enable"] = false,
["style"] = "Pixel Glow",
["color"] = {
0.09,
0.52,
0.82,
0.9,
},
["size"] = 1,
},
["tags"] = {
["name"] = "",
["power"] = "",
["level"] = "",
["health"] = "",
["title"] = "",
},
["color"] = {
["healthClass"] = false,
["power"] = false,
["healthColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["border"] = false,
["health"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderClass"] = false,
["powerClass"] = false,
["powerColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["nameOnly"] = false,
["alpha"] = -1,
["flash"] = {
["enable"] = false,
["class"] = false,
["speed"] = 4,
["color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["hide"] = false,
["usePortrait"] = false,
["texture"] = {
["enable"] = false,
["texture"] = "ElvUI Norm",
},
},
["triggers"] = {
["known"] = {
["playerSpell"] = false,
["spells"] = {
},
["notKnown"] = false,
},
["class"] = {
},
["notInParty"] = false,
["notCharmed"] = false,
["role"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["isPossessed"] = false,
["notResting"] = false,
["level"] = false,
["isNotPet"] = false,
["threat"] = {
["good"] = false,
["offTankBadTransition"] = false,
["bad"] = false,
["offTank"] = false,
["enable"] = false,
["offTankGoodTransition"] = false,
["badTransition"] = false,
["goodTransition"] = false,
},
["overHealthThreshold"] = 0,
["playerCanAttack"] = false,
["items"] = {
},
["bossMods"] = {
["missingAuras"] = false,
["missingAura"] = false,
["hasAura"] = false,
["auras"] = {
},
},
["isConnected"] = false,
["creatureType"] = {
["Dragonkin"] = false,
["Humanoid"] = false,
["Elemental"] = false,
["Critter"] = false,
["enable"] = false,
["Gas Cloud"] = false,
["Totem"] = false,
["Non-combat Pet"] = false,
["Wild Pet"] = false,
["Demon"] = false,
["Not specified"] = false,
["Undead"] = false,
["Aberration"] = false,
["Giant"] = false,
["Beast"] = false,
["Mechanical"] = false,
},
["notInRaid"] = false,
["isBeingResurrected"] = false,
["requireTarget"] = false,
["isUnconscious"] = false,
["healthThreshold"] = false,
["unitRole"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["hasTitleNPC"] = false,
["keyMod"] = {
["Alt"] = false,
["LeftControl"] = false,
["RightShift"] = false,
["enable"] = false,
["RightAlt"] = false,
["LeftShift"] = false,
["Modifier"] = false,
["Shift"] = false,
["RightControl"] = false,
["LeftAlt"] = false,
["Control"] = false,
},
["noTitleNPC"] = false,
["healthUsePlayer"] = false,
["raidTarget"] = {
["circle"] = false,
["square"] = false,
["diamond"] = false,
["cross"] = false,
["star"] = false,
["triangle"] = false,
["skull"] = false,
["moon"] = false,
},
["isQuest"] = false,
["underPowerThreshold"] = 0,
["instanceDifficulty"] = {
["dungeon"] = {
["normal"] = false,
["mythic+"] = false,
["heroic"] = false,
["timewalking"] = false,
["mythic"] = false,
},
["raid"] = {
["normal"] = false,
["legacy25normal"] = false,
["heroic"] = false,
["legacy10normal"] = false,
["legacy10heroic"] = false,
["legacy25heroic"] = false,
["lfr"] = false,
["timewalking"] = false,
["mythic"] = false,
},
},
["minlevel"] = 0,
["notDeadOrGhost"] = false,
["overPowerThreshold"] = 0,
["notMyGuild"] = false,
["faction"] = {
["Horde"] = false,
["Alliance"] = false,
["Neutral"] = false,
},
["location"] = {
["zoneNamesEnabled"] = false,
["subZoneNamesEnabled"] = false,
["zoneNames"] = {
},
["mapIDs"] = {
},
["subZoneNames"] = {
},
["instanceIDs"] = {
},
["mapIDEnabled"] = false,
["instanceIDEnabled"] = false,
},
["isTapDenied"] = false,
["debuffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["fromPet"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromMe"] = false,
["hasNoDispellable"] = false,
["hasDispellable"] = false,
},
["instanceType"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = false,
["none"] = false,
},
["inCombatUnit"] = false,
["notOthersPet"] = false,
["amountBelow"] = 0,
["isCharmed"] = false,
["powerThreshold"] = false,
["inVehicle"] = false,
["outOfCombat"] = false,
["isNotPlayerControlled"] = false,
["notTarget"] = false,
["nameplateType"] = {
["player"] = false,
["enemyNPC"] = false,
["enemyPlayer"] = false,
["enable"] = false,
["friendlyPlayer"] = false,
["friendlyNPC"] = false,
},
["isOthersPet"] = false,
["maxlevel"] = 0,
["slots"] = {
},
["notQuest"] = false,
["powerUsePlayer"] = false,
["notPossessed"] = false,
["outOfVehicleUnit"] = false,
["outOfCombatUnit"] = false,
["reactionType"] = {
["enabled"] = false,
["reputation"] = false,
["friendly"] = false,
["revered"] = false,
["honored"] = false,
["hostile"] = false,
["unfriendly"] = false,
["exalted"] = false,
["neutral"] = false,
["hated"] = false,
},
["buffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["hasNoStealable"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromPet"] = false,
["fromMe"] = false,
["hasStealable"] = false,
},
["playerCanNotAttack"] = false,
["inCombat"] = false,
["isNotTapDenied"] = false,
["isNotPvP"] = false,
["isNotOwnedByPlayer"] = false,
["noTarget"] = false,
["names"] = {
},
["inParty"] = false,
["inPetBattle"] = false,
["curlevel"] = 0,
["isPlayerControlled"] = false,
["isOwnedByPlayer"] = false,
["inVehicleUnit"] = false,
["inMyGuild"] = false,
["isPet"] = false,
["priority"] = 1,
["inRaid"] = false,
["isResting"] = false,
["targetMe"] = false,
["classification"] = {
["elite"] = false,
["normal"] = false,
["trivial"] = false,
["minus"] = false,
["worldboss"] = false,
["rareelite"] = false,
["rare"] = false,
},
["notConnected"] = false,
["notTrivial"] = false,
["isTrivial"] = false,
["notBeingResurrected"] = false,
["notPetBattle"] = false,
["isPvP"] = false,
["isDeadOrGhost"] = false,
["questBoss"] = false,
["outOfVehicle"] = false,
["isConscious"] = false,
["cooldowns"] = {
["mustHaveAll"] = false,
["names"] = {
},
},
["casting"] = {
["isChanneling"] = false,
["notSpell"] = false,
["isCasting"] = false,
["notChanneling"] = false,
["spells"] = {
},
["notCasting"] = false,
["interruptible"] = false,
},
["underHealthThreshold"] = 0,
["amountAbove"] = 0,
},
},
["ElvUI_Boss"] = {
["actions"] = {
["glow"] = {
["speed"] = 0.3,
["lines"] = 8,
["frameLevel"] = 5,
["useColor"] = true,
["enable"] = false,
["style"] = "Pixel Glow",
["color"] = {
0.09,
0.52,
0.82,
0.9,
},
["size"] = 1,
},
["tags"] = {
["name"] = "",
["power"] = "",
["level"] = "",
["health"] = "",
["title"] = "",
},
["color"] = {
["healthClass"] = false,
["power"] = false,
["healthColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["border"] = false,
["health"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderClass"] = false,
["powerClass"] = false,
["powerColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["nameOnly"] = false,
["alpha"] = -1,
["flash"] = {
["enable"] = false,
["class"] = false,
["speed"] = 4,
["color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["hide"] = false,
["texture"] = {
["enable"] = false,
["texture"] = "ElvUI Norm",
},
},
["triggers"] = {
["known"] = {
["playerSpell"] = false,
["spells"] = {
},
["notKnown"] = false,
},
["class"] = {
},
["notInParty"] = false,
["notCharmed"] = false,
["role"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["isPossessed"] = false,
["notResting"] = false,
["isNotPet"] = false,
["threat"] = {
["good"] = false,
["offTankBadTransition"] = false,
["bad"] = false,
["offTank"] = false,
["enable"] = false,
["offTankGoodTransition"] = false,
["badTransition"] = false,
["goodTransition"] = false,
},
["overHealthThreshold"] = 0,
["playerCanAttack"] = false,
["items"] = {
},
["bossMods"] = {
["missingAuras"] = false,
["missingAura"] = false,
["hasAura"] = false,
["auras"] = {
},
},
["isConnected"] = false,
["creatureType"] = {
["Dragonkin"] = false,
["Humanoid"] = false,
["Elemental"] = false,
["Critter"] = false,
["enable"] = false,
["Gas Cloud"] = false,
["Totem"] = false,
["Non-combat Pet"] = false,
["Wild Pet"] = false,
["Demon"] = false,
["Not specified"] = false,
["Undead"] = false,
["Aberration"] = false,
["Giant"] = false,
["Beast"] = false,
["Mechanical"] = false,
},
["notInRaid"] = false,
["isBeingResurrected"] = false,
["requireTarget"] = false,
["isUnconscious"] = false,
["healthThreshold"] = false,
["unitRole"] = {
["tank"] = false,
["damager"] = false,
["healer"] = false,
},
["hasTitleNPC"] = false,
["keyMod"] = {
["Alt"] = false,
["LeftControl"] = false,
["RightShift"] = false,
["enable"] = false,
["RightAlt"] = false,
["LeftShift"] = false,
["Modifier"] = false,
["Shift"] = false,
["RightControl"] = false,
["LeftAlt"] = false,
["Control"] = false,
},
["noTitleNPC"] = false,
["healthUsePlayer"] = false,
["raidTarget"] = {
["circle"] = false,
["square"] = false,
["diamond"] = false,
["cross"] = false,
["star"] = false,
["triangle"] = false,
["skull"] = false,
["moon"] = false,
},
["isQuest"] = false,
["underPowerThreshold"] = 0,
["instanceDifficulty"] = {
["dungeon"] = {
["normal"] = false,
["mythic+"] = false,
["heroic"] = false,
["timewalking"] = false,
["mythic"] = false,
},
["raid"] = {
["normal"] = false,
["legacy25normal"] = false,
["heroic"] = false,
["legacy10normal"] = false,
["legacy10heroic"] = false,
["legacy25heroic"] = false,
["lfr"] = false,
["timewalking"] = false,
["mythic"] = false,
},
},
["minlevel"] = 0,
["notDeadOrGhost"] = false,
["overPowerThreshold"] = 0,
["notMyGuild"] = false,
["faction"] = {
["Horde"] = false,
["Alliance"] = false,
["Neutral"] = false,
},
["location"] = {
["zoneNamesEnabled"] = false,
["subZoneNamesEnabled"] = false,
["zoneNames"] = {
},
["mapIDs"] = {
},
["subZoneNames"] = {
},
["instanceIDs"] = {
},
["mapIDEnabled"] = false,
["instanceIDEnabled"] = false,
},
["isTapDenied"] = false,
["debuffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["fromPet"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromMe"] = false,
["hasNoDispellable"] = false,
["hasDispellable"] = false,
},
["instanceType"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = false,
["none"] = false,
},
["inCombatUnit"] = false,
["notOthersPet"] = false,
["amountBelow"] = 0,
["isCharmed"] = false,
["powerThreshold"] = false,
["inVehicle"] = false,
["inVehicleUnit"] = false,
["slots"] = {
},
["notTarget"] = false,
["nameplateType"] = {
["player"] = false,
["enemyNPC"] = false,
["enemyPlayer"] = false,
["enable"] = false,
["friendlyPlayer"] = false,
["friendlyNPC"] = false,
},
["isOthersPet"] = false,
["notQuest"] = false,
["isConscious"] = false,
["isNotTapDenied"] = false,
["powerUsePlayer"] = false,
["isNotOwnedByPlayer"] = false,
["outOfVehicleUnit"] = false,
["isPvP"] = false,
["outOfCombatUnit"] = false,
["buffs"] = {
["minTimeLeft"] = 0,
["mustHaveAll"] = false,
["hasNoStealable"] = false,
["missing"] = false,
["onPet"] = false,
["names"] = {
},
["onMe"] = false,
["maxTimeLeft"] = 0,
["fromPet"] = false,
["fromMe"] = false,
["hasStealable"] = false,
},
["isPet"] = false,
["inCombat"] = false,
["isOwnedByPlayer"] = false,
["isNotPvP"] = false,
["outOfCombat"] = false,
["noTarget"] = false,
["playerCanNotAttack"] = false,
["inParty"] = false,
["inPetBattle"] = false,
["names"] = {
},
["isPlayerControlled"] = false,
["reactionType"] = {
["enabled"] = false,
["reputation"] = false,
["friendly"] = false,
["revered"] = false,
["honored"] = false,
["hostile"] = false,
["unfriendly"] = false,
["exalted"] = false,
["neutral"] = false,
["hated"] = false,
},
["isTrivial"] = false,
["isTarget"] = false,
["underHealthThreshold"] = 0,
["inRaid"] = false,
["isResting"] = false,
["targetMe"] = false,
["classification"] = {
["elite"] = false,
["normal"] = false,
["trivial"] = false,
["minus"] = false,
["worldboss"] = false,
["rareelite"] = false,
["rare"] = false,
},
["notConnected"] = false,
["notTrivial"] = false,
["inMyGuild"] = false,
["notBeingResurrected"] = false,
["notPetBattle"] = false,
["amountAbove"] = 0,
["notPossessed"] = false,
["questBoss"] = false,
["outOfVehicle"] = false,
["isNotPlayerControlled"] = false,
["cooldowns"] = {
["mustHaveAll"] = false,
["names"] = {
},
},
["casting"] = {
["isChanneling"] = false,
["notSpell"] = false,
["isCasting"] = false,
["notChanneling"] = false,
["spells"] = {
},
["notCasting"] = false,
["interruptible"] = false,
},
["isDeadOrGhost"] = false,
["maxlevel"] = 0,
},
},
},
},
},
["faction"] = {
["Ревущий фьорд"] = {
["Бимладен"] = "Alliance",
},
["Свежеватель Душ"] = {
["Вольтчара"] = "Horde",
},
},
["namespaces"] = {
["LibDualSpec-1.0"] = {
},
},
}
ElvPrivateDB = {
["profileKeys"] = {
["Бимладен - Ревущий фьорд"] = "Бимладен - Ревущий фьорд",
["Вольтчара - Свежеватель Душ"] = "Вольтчара - Свежеватель Душ",
},
["profiles"] = {
["Бимладен - Ревущий фьорд"] = {
["general"] = {
["nameplateLargeFont"] = "ITCAvantGardeGothicDemi",
["dmgfont"] = "ITCAvantGardeGothicDemi",
["chatBubbleFontSize"] = 10,
["namefont"] = "ITCAvantGardeGothicDemi",
["minimap"] = {
["hideTracking"] = true,
},
["chatBubbleFont"] = "ITCAvantGardeGothicDemi",
["nameplateFont"] = "ITCAvantGardeGothicDemi",
["chatBubbles"] = "nobackdrop",
["chatBubbleFontOutline"] = "SHADOWOUTLINE",
["raidUtility"] = false,
},
["nameplates"] = {
["enable"] = false,
},
["install_complete"] = 13.45,
},
["Вольтчара - Свежеватель Душ"] = {
["install_complete"] = 13.75,
},
},
}
