
GlobalIgnoreDB = {
["filterCount"] = {
0,
6,
0,
0,
0,
0,
0,
0,
0,
0,
},
["skipYourself"] = false,
["openWithFriends"] = true,
["skipPrivate"] = true,
["autoCount"] = 3,
["floodFilter"] = 0,
["syncInfo"] = {
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
"Beamladen-Twistingnether@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
"Мальдика-СвежевательДуш@1",
"Алианкано-СвежевательДуш@1",
"Джуставар-СвежевательДуш@1",
"Прециза-СвежевательДуш@1",
"Виандисто-СвежевательДуш@1",
"Спленда-СвежевательДуш@1",
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
{
},
},
["trackChanges"] = true,
["sameserver"] = true,
["attachFriends"] = true,
["revision"] = 1,
["expList"] = {
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
},
["defexpire"] = 0,
["filterDesc"] = {
"Filter \"Anal\" Spammers",
"Filter Thunderfury linking",
"Filter Mythic+ Sellers",
"Filter Tradeskill Sellers",
"Filter Power Leveling Sellers",
"Filter Guild Recruitment",
"Filter Community Recruitment",
"Filter WTS",
"Filter Chinese/Korean/Japanese",
"Filter American Politics",
},
["showIgnoreDebug"] = false,
["spamFilter"] = true,
["typeList"] = {
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
"player",
},
["invertSpam"] = false,
["ignoreList"] = {
"Angelofpure-Silvermoon",
"Bullfront-Draenor",
"Catserk-Draenor",
"Darrkshield-Kazzak",
"Dhbusay-Hyjal",
"Diabólus-Antonidas",
"Dreiixee-Blackrock",
"Durial-Ragnaros",
"Fvbbe-Tarrenmill",
"Golemlord-Draenor",
"Greatpush-Ravencrest",
"Grimurion-Thrall",
"Hiiamtank-Kazzak",
"Hypnios-Khazmodan",
"Inksäras-Draenor",
"Ironsmelter-Burninglegion",
"Kacpii-Turalyon",
"Kamratpil-Kazzak",
"Kamîkadze-Draenor",
"Kococo-Tarrenmill",
"Miawferal-Ravencrest",
"Nanozboub-Hyjal",
"Nightfrâme-Blackrock",
"Nukeskull-Tarrenmill",
"Nèrf-Draenor",
"Palacuruh-Nemesis",
"Pawbubble-Burninglegion",
"Plotniybass-Tarrenmill",
"Radmagetwo-Tarrenmill",
"Rifflash-Ysondre",
"Sadstoryy-Draenor",
"Sangiorgio-Nemesis",
"Sesiana-Frostmane",
"Stjernxd-Kazzak",
"Strakos-Draenor",
"Trashna-Blackmoore",
"Unlucki-Blackmoore",
"Uouch-Kazzak",
"Ursyl-Tarrenmill",
"Блээйз-Гордунни",
"Бодяо-Гордунни",
"Ввфортуна-Гордунни",
"Громел-Гордунни",
"Дженденлоу-Ревущийфьорд",
"Миранисаа-Гордунни",
"Ronaldosiu-Ravencrest",
"Сейтенни-Гордунни",
"Jo-Themaelstrom",
"Тевеон-РевущийФьорд",
"Synkinn-Thrall",
"Éjsiy-Drak'thul",
"Mehov-Twistingnether",
"Onlysins-Kazzak",
"Darkseêr-Silvermoon",
"Стоксси-Гордунни",
"Haikø-Silvermoon",
"Ancholy-Burninglegion",
"Ariiaus-Hyjal",
"Beinstrecker-Blackrock",
"Claptofit-Archimonde",
"Trusted-Twistingnether",
"Лостмилано-Гордунни",
"Флэймборн-Гордунни",
"Gøldstrïke-Silvermoon",
"Spandie-Silvermoon",
"Hugoesp-Kazzak",
"Mistyteria-Drak'thul",
"Mayanu-Kazzak",
"Ackyrose-Sanguino",
"Mawep-Nozdormu",
"Javid-Kazzak",
"Assire-Terokkar",
"Tígér-Silvermoon",
"Ironear-Blackmoore",
"Johännä-Dalaran",
"Torckhel-Hyjal",
"Gripzumbeer-Blackhand",
"Colorzx-Twistingnether",
"Попца-Гордунни",
"Holydeeds-Antonidas",
"Hotmage-Kazzak",
"Nympal-Tarrenmill",
"Nistia-Hyjal",
"Nomananocry-Ragnaros",
"Voltyria-Blackrock",
"Xragonaria-Blackrock",
"Змейкек-Ревущийфьорд",
"Dragdo-Nemesis",
"Agrow-Ragnaros",
"Bcmd-Silvermoon",
"Tschixi-Thrall",
"Equilibrio-Sanguino",
"Suicidedrive-Ysondre",
"Bunyaa-Thrall",
"Zerudrake-Zul'jin",
"Mizujin-Sanguino",
"Fluvia-Eredar",
"Launchforge-Silvermoon",
"Imbaep-Tarrenmill",
"Hajduk-Kazzak",
"Akaya-Echsenkessel",
"Gubpriest-Ragnaros",
"Curunìr-Hyjal",
"Hýgor-Kazzak",
"Ostore-Tarrenmill",
"Абзиза-Ревущийфьорд",
"Свилайх-Гордунни",
"Showtímé-Blackhand",
"Мисуха-Гордунни",
"Snackety-Twistingnether",
"Broxqt-Twistingnether",
"Jozzyvoker-Ragnaros",
"Скифул-РевущийФьорд",
"Пассивно-РевущийФьорд",
"Pitareca-Aggra(PORTUGUês)",
"Vtouch-Kazzak",
"Фообосс-Ревущийфьорд",
"Holyhandnade-Kazzak",
"Discopablo-Kazzak",
"Турбогей-Гордунни",
"Калюцифер-Гордунни",
"Laloumiere-Dalaran",
"Laehrekove-Thrall",
"Белаяобойма-Гордунни",
"Тарапуничка-Дракономор",
"Фулысконя-Седогрив",
"Spirithealer-Uldaman",
"Ahdistaja-Sylvanas",
"Artium-Hyjal",
"Toretto-Azshara",
"Funx-Stormreaver",
"Aoedragon-Stormscale",
"Valie-Dalaran",
"Dobermante-Twistingnether",
"Cerseyi-Hyjal",
"Yum-Anetheron",
"Nostfanboy-Stormscale",
"Charmendder-Draenor",
"Whimpy-Eredar",
"Firemidget-Kazzak",
"Karume-C'thun",
"Arkangyal-Twistingnether",
"Kagesmølf-Silvermoon",
"Zythris-Zul'jin",
"Kongozuna-Tarrenmill",
"Dzonamvp-Draenor",
"Splî-Silvermoon",
"Bethoni-Blackrock",
"Lyonoss-Ragnaros",
"Râchendrache-Blackmoore",
"Beardedbroo-Turalyon",
"Föryou-Stormscale",
"Kazunne-Sargeras",
"Lightdk-Stormscale",
"Mgck-Tarrenmill",
"Nefarius-Burninglegion",
"Recua-Ragnaros",
"Stahlschädel-Antonidas",
"Thunderfil-Silvermoon",
"Todiedk-Tarrenmill",
"Trapgodx-Tarrenmill",
"Zóë-Kazzak",
"Гардана-Ревущийфьорд",
"Дардалер-Гордунни",
"Квэнтин-Ревущийфьорд",
"Кррэш-Ревущийфьорд",
"Крэйвэн-Галакронд",
"Ньяса-Голдринн",
"Охотникнадуш-ЧерныйШрам",
"Усури-Ревущийфьорд",
"Evesse-Tarrenmill",
"Sashagoðx-Zul'jin",
"Deadhtank-Aggra(PORTUGUês)",
"Фокусразума-Гордунни",
"Loudbass-Tarrenmill",
"Diamondteár-Twistingnether",
"Биньки-Галакронд",
"Eritreith-Eonar",
"Andyblossom-Silvermoon",
"Jamammon-Sanguino",
"Bozzedh-Tarrenmill",
"Circular-Stormscale",
"Teuflum-Stormscale",
"Knowmedh-Blackhand",
"Overtrap-Twistingnether",
"Rayxxray-Twistingnether",
"Ururusha-Silvermoon",
"Эвелеона-Гордунни",
"Hårdpølse-Twistingnether",
"Yeszir-Twistingnether",
"Iddotdat-Tarrenmill",
"Womannen-Eonar",
"Dronesdh-Tarrenmill",
"Itsmeluna-Twistingnether",
"Эвелеона-Ревущийфьорд",
"Nnoggiedh-Twistingnether",
"Erafiend-Twistingnether",
"Djokovich-Kazzak",
"Distribute-Draenor",
"Cátzzy-Tarrenmill",
"Мистут-Галакронд",
"Sarznn-Twistingnether",
"Gachidemon-Burninglegion",
"Zòrtaxstm-Ravencrest",
"Dinodeath-Twistingnether",
"Coiler-Blackrock",
"Fearnothing-Stormscale",
"Каннака-Ревущийфьорд",
"Растомаг-СвежевательДуш",
"Асоко-СвежевательДуш",
"Дестрооер-СвежевательДуш",
"Нейджик-СвежевательДуш",
"Пассивно-СвежевательДуш",
"Фулысконя-СвежевательДуш",
"Никдерфорд-Гордунни",
"Fåct-Hyjal",
"Déathpower-Silvermoon",
"Starwár-Kazzak",
"Lenuxia-Blackrock",
"Søxya-Thrall",
"Partyinmyass-Blackhand",
"Zulakhan-Ragnaros",
"Tératome-Hyjal",
"Dkbyte-Hyjal",
"Sitting-Hyjal",
"Aimfacka-Twistingnether",
"Falaha-Stormscale",
"Thaedran-Eitrigg",
"Lilfreaky-Blackrock",
"Совинушкин-Гордунни",
"Downrank-Draenor",
"Behelithar-Silvermoon",
"Åegwynn-Sanguino",
"Pouletmorph-Archimonde",
"Kiidaadk-Twistingnether",
"Starkus-Sylvanas",
"Iul-Stormscale",
"Mkom-Ravencrest",
"Tarrda-Blackhand",
"Erruthos-Twistingnether",
"Silvanor-Antonidas",
"Koksniffa-Burninglegion",
"Jaraz-Ragnaros",
"Revmagic-Ragnaros",
"Galevorn-Draenor",
"Volthalak-Kel'thuzad",
"Chawman-Draenor",
"Naviic-Ravencrest",
"Yleni-Twistingnether",
"Singlelife-Ravencrest",
"Dahtat-Outland",
"Adranis-Hyjal",
"Holycarrier-Tarrenmill",
"Fairrfm-Burninglegion",
"Duvids-Drak'thul",
"Ayéfinezerbe-Dalaran",
"Fehirtotem-Drak'thul",
"Behemoth-Burningsteppes",
"Tricksteriva-Turalyon",
"Yutisham-Zul'jin",
"Disneyfan-Kazzak",
"Galeth-Ragnaros",
"Boauruk-Mal'ganis",
"Wylenn-Ragnaros",
"Aethan-Kazzak",
"Cruiserguru-Twistingnether",
"Gódsgift-Ravencrest",
"Lazyysham-Burninglegion",
"Storadave-Ravencrest",
"Supcopium-Ysondre",
"Shetanî-Thrall",
"Noirnainfer-Dalaran",
"Katkaez-Tarrenmill",
"Nasas-Ravencrest",
"Мяурицуc589f-СвежевательДуш",
"Bigtilted-Draenor",
"Horagor-Silvermoon",
"Holypang-Twistingnether",
"Papillon-Rajaxx",
"Retdemption-Tarrenmill",
"Extaâ-Ysondre",
"Kasajewl-Outland",
"Илюша-Гордунни",
"Гадюка-Ревущийфьорд",
"Aujin-Twistingnether",
"Pauliezugzug-Stormscale",
"Dza-Antonidas",
"Extrasauer-Aegwynn",
"Илюша-Ревущийфьорд",
"Shamerr-Turalyon",
"Dîbs-Hyjal",
"Axioow-Twistingnether",
"Devilshand-Eredar",
"Saknom-Stormscale",
"Respectino-Outland",
"Шинсо-Гордунни",
"Скибидипопыч-Гордунни",
"Therosia-Twistingnether",
"Whiitebear-Stormscale",
"Eláx-Thrall",
"Шинсо-Ревущийфьорд",
"Dadoutside-Kazzak",
"Ohmslaw-Stormscale",
"Ddk-Aegwynn",
"Intydhh-Hyjal",
"Xmfdh-Kazzak",
"Chimatsu-Eredar",
"Родхар-СвежевательДуш",
"Dopefiend-Draenor",
"Jahbrowski-Ysondre",
"Zevlis-Burningblade",
"Металхарт-Термоштепсель",
"Батуссай-СвежевательДуш",
"Анастасьён-СвежевательДуш",
"Манчага-СвежевательДуш",
"Нэровар-СвежевательДуш",
"Сугробикк-СвежевательДуш",
},
["autoTime"] = 600,
["autoIgnore"] = true,
["factionList"] = {
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Alliance",
"Alliance",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Horde",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Alliance",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Alliance",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Alliance",
"Horde",
"Horde",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Alliance",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
"Horde",
},
["delList"] = {
"Лостмилано-СвежевательДуш",
"Флэймборн-СвежевательДуш",
"Coiler-СвежевательДуш",
"Fearnothing-СвежевательДуш",
"Каннака-СвежевательДуш",
"Hýgor-СвежевательДуш",
"Ostore-СвежевательДуш",
"Абзиза-СвежевательДуш",
"Медиваль-СвежевательДуш",
"Никдерфорд-Ревущийфьорд",
"Déathpower-Ревущийфьорд",
"Fåct-Ревущийфьорд",
"Starwár-Ревущийфьорд",
"Lenuxia-Ревущийфьорд",
"Partyinmyass-Ревущийфьорд",
"Søxya-Ревущийфьорд",
"Dkbyte-Ревущийфьорд",
"Tératome-Ревущийфьорд",
"Zulakhan-Ревущийфьорд",
"Sitting-СвежевательДуш",
"Åegwynn-СвежевательДуш",
"Falaha-Ревущийфьорд",
"Lilfreaky-Ревущийфьорд",
"Thaedran-Ревущийфьорд",
"Pouletmorph-СвежевательДуш",
"Aimfacka-Ревущийфьорд",
"Mkom-СвежевательДуш",
"Iul-СвежевательДуш",
"Jaraz-СвежевательДуш",
"Revmagic-СвежевательДуш",
"Silvanor-СвежевательДуш",
"Tarrda-СвежевательДуш",
"Koksniffa-СвежевательДуш",
"Naviic-СвежевательДуш",
"Singlelife-СвежевательДуш",
"Chawman-СвежевательДуш",
"Erruthos-СвежевательДуш",
"Galevorn-СвежевательДуш",
"Kiidaadk-СвежевательДуш",
"Starkus-СвежевательДуш",
"Volthalak-СвежевательДуш",
"Yleni-СвежевательДуш",
"Adranis-СвежевательДуш",
"Dahtat-СвежевательДуш",
"Fairrfm-СвежевательДуш",
"Duvids-СвежевательДуш",
"Holycarrier-СвежевательДуш",
"Disneyfan-СвежевательДуш",
"Ayéfinezerbe-СвежевательДуш",
"Behemoth-СвежевательДуш",
"Fehirtotem-СвежевательДуш",
"Yutisham-СвежевательДуш",
"Boauruk-СвежевательДуш",
"Galeth-СвежевательДуш",
"Батуссай-СвежевательДуш",
"Аккбайер-СвежевательДуш",
"Русядру-СвежевательДуш",
"Свилайх-СвежевательДуш",
"Скифул-СвежевательДуш",
"Турбогей-СвежевательДуш",
"Unsteddy-Tarrenmill",
"Dvigshamik-Drak'thul",
"Cruiserguru-СвежевательДуш",
"Gódsgift-СвежевательДуш",
"Lazyysham-СвежевательДуш",
"Shetanî-СвежевательДуш",
"Storadave-СвежевательДуш",
"Supcopium-СвежевательДуш",
"Noirnainfer-СвежевательДуш",
"Sickya-Kazzak",
"Nasas-СвежевательДуш",
"Aethan-Ревущийфьорд",
"Downrank-Ревущийфьорд",
"Tricksteriva-Ревущийфьорд",
"Papillon-Ревущийфьорд",
"Aujin-Ревущийфьорд",
"Bigtilted-Ревущийфьорд",
"Extaâ-Ревущийфьорд",
"Holypang-Ревущийфьорд",
"Kasajewl-Ревущийфьорд",
"Katkaez-Ревущийфьорд",
"Retdemption-Ревущийфьорд",
"Силонер-Гордунни",
"Behelithar-Ревущийфьорд",
"Dza-Ревущийфьорд",
"Extrasauer-Ревущийфьорд",
"Horagor-Ревущийфьорд",
"Pauliezugzug-Ревущийфьорд",
"Скибидипопыч-Ревущийфьорд",
"Axioow-Ревущийфьорд",
"Devilshand-Ревущийфьорд",
"Dîbs-Ревущийфьорд",
"Eláx-Ревущийфьорд",
"Respectino-Ревущийфьорд",
"Saknom-Ревущийфьорд",
"Shamerr-Ревущийфьорд",
"Therosia-Ревущийфьорд",
"Whiitebear-Ревущийфьорд",
"Евгенийо-Ревущийфьорд",
"Dopefiend-СвежевательДуш",
},
["notes"] = {
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Протопал. Вроде ок, но очень своеобразный чел. Ничего не затаймили из 4-5 ранов.",
"",
"",
"[Shadow priest] Не жмет сейвы и ушел оффлайн в ключе",
"2 раза умер на 3 боссе в подгнилье, хотел диспела которого нет в пати. Конченный",
"Приест долбоеб. Не дамажит и умирает как тварь конченная!",
"Протпал. Долбоеб умер 3 раза на 3 боссе в подгнилье не закрывался щитом и собирал грибы. И ливнул!",
"Прист. Долбоеб не дамажит и не заходил в мили в нелтарии на 2 боссе",
"Элем, который напиздел что энх в итоге конченный еблан оказался без дпс и киков",
"Танк друид. В логове на первом паке залез в текстуры, потом развернул клив в пати. И ливнул сказал низкий дпс.",
"ШП. Не дамажит, не контролит, умирает.",
"Протопал. Не зашел на жабе 2 раза в чертогах в круг и босс дважды забюафался на +50% и был вайп. Чкел даже не понял от чего сдох",
"ШП. Еблан сломал кей на ласте в чертогах не прожал ни дисперсию ни молитву",
"Ретропал. Ливнул посередине инста.",
"",
"",
"",
"",
"",
"",
"",
"ШП. Не диспелил на 1 боссе в чертогах. И такой себе дамаг.",
"Хпал. Не дамажит и по мане сливается.",
"ШП. Умер в паке без БРов и лежал просто. И ливнул потом.",
"Протопал. Роут просто дерьмо. 3 вайпа на его подпулах конченных.",
"Хпал. 3 раза умер на ласте в нелтарии. Слабый.",
"Холипал. Ливнул с ключа.",
"Холиприст. Умирает по кд. Очень слабый. Не дамажит.",
"Друид танк. На ласт боссе после того как таймер закончился ливнул посреди босса.",
"ДЦ. Адды на нараксе забагались, был вайп.  Ливнул с ключа, хотя был таймер еще.",
"Друид танк. Подпулил пак и сдоъ как собака и ливнул сразу.",
"Друид танк. Плохо живет.",
"ШП. Просто ливнул после первого босса в вортексе.",
"ШП. Вообще не дамажит. От слова ОХУЕТЬ КАК НЕ ДАМАЖИТ.",
"ШП.Не дамажит вообще и тупой к тому же.",
"ШП. Не дамажит нихуя. Просто 0.",
"Холипал. Слабо хилит. Прошли в тайм, но еле прохиливал 3 босса в нелтарии 110к хпс.",
"Холипал. Не дамажит аддов на нараксе. 500к только",
"Фаермаг. Не дамажит совсем. Оверол до дракона в вортексе 170к под эвокером",
"Холипал. 0 Урона в аддов на рокморе в логове. Конченный",
"Холипал. Не хилит нихуя.",
"ШП. На первом паке в подгнилье умер 3 раза от личинки и ливнул. чел 50к дпс.",
"Холипал. Помойка.",
"ШП. Помойка.",
"Друид танк. Плохо живет.",
"Друид танк. Долбоеб в чертогах взял дракона на мосту с кучей кастеров и никто не кикал касты разделения.",
"ШП. Просто конченное ебло без дпс. Умирает в каждом паке.",
"Друид танк. Просто помойка неживучая. И пулы долбоеба ебаного.",
"ШП. Слабый мусор не дамажит. Ливнул после диплита инстантно.",
"Друид танк. Спешит пулить и не живет сам.",
"ШП. Ебло вышло на боссе",
"ШП. Еблан не диспелит в чертогах на 1 боссе",
"Ауг. Еблан не знает как работают цепи в нелтарии. Со своим другом танком сломали кей.",
"Друид танк. Еблан не знает как работают цепи в нелтарии. Со своим другом аугом сломали кей. Спулил комнату когда у всех дебафы.",
"Холик. Еблан конченный нихуя не может.",
"Холипал. С пула афк, не хилил. Умер просто.",
"ШП. Еблан сдох в первом же паке. 0 дпс.",
"Вар. Дамажит норм, но русофоб конченный.",
"ШП. Нет дпс, не читает чат, умирает.",
"ШП. Еблан не диспелит щиты",
"Ну +/- Танк друид. После 1 запула пошел переодевать шмот. Проебали время.",
"",
"",
"",
"ШП. Не дамажит, кнопки не жмет. Массдиспелить не умеет.",
"ШП. Еблан не диспелит на 1 боссе чертог. Не взял короткий масс диспел.",
"ШП. Уебок без дпс. Еще и сдох перед ласт боссом в вершине. Ждали уебана 16с не успели",
"Хпал. Ебло.",
"ШП. Типичный уебан",
"Ауг. Еблан конченный. Умирает и БЛ не дает",
"Ауг. Сказали что долбоеб (с) Саламыч",
"ШП. Не диспелит бурстинг + не дамажит",
"Фмаг. ВЫлетел и не зашел.",
"ШП. Конченный хуесос. Абсолютный еблан.",
"Рога. Долбоеб редкостный",
"ХПал. Ебло тупое. Нихуя не может",
"Ршаман. Конченный еблан + дисконнектнуло паскуду.",
"Хпал. Не хилит, не дамажит. Конченный уебан",
"Фмаг. Тупой как пробка.",
"ДЦ.  Оффнулся мразь",
"Ауг. Аутист. Не снимает блиду. Умирает по кд.",
"ШП. Кикает касты как уебан. Умирает по кд. Дпса 0",
"",
"",
"Миствивер. Ливнул с ключа. Шли в тайм.",
"ШП. Не дамажит. Не свичит в аддов на ласте в логове.",
"ШП. В целом норм, но очень мало дамажит.",
"БМ. Баер дпс ниже ауга.",
"ФМаг. В целом ок, но дпса очень мало.",
"Ауг. Ребенок играет.",
"MW монк. Клоун без маны и подпуливает",
"ФВар. Не жмет сейвы, не свичится.",
"Хпал. Слабый умирающий хуйлан.",
"MW. Конченный хуйлан. Умирал по кд.",
"Хпал. Еблуша не хилит.",
"Ауг. Ливнул с ключа.",
"ШП. Норм но дпса просто нет.",
"Фмаг. Долбоеб ливающий.",
"БМ. Конченный уебан",
"Ауг. Ливнул с ласт босса.",
"ВДХ. Еблан конченный. Лоускилл",
"ВДХ. Уебище редкое.",
"Протпал. Вышел с ключа после вайпа на 1 боссе в низе рассвета, хотя времени до жопы было.",
"БДК. Конченный долбоеб",
"Протпал. Еблан не диспелит афикс и не выживает. Умер на паке и на морхи 2 раза.",
"ВДХ. Еблан ливнул.",
"ВДХ. Долбоеб который не понимает игру и пиздит хуйню. Такого лучше не брать.",
"Ауг. Низкий аптайм мощи.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ауг. Дисконектнулся на боссе и позже после смерти танка ливнул. 54% черная мощь аптайм",
"Ауг. Конченное ебло ливнуло посреди босса.",
"ВДХ. Ебло умер на 3 боссе в троне. 2 раза.",
"Фмаг. Мастер байтов в цветении.",
"ПротПал. Слабый даун. Умер на свинье в маноре от луж аддов. Пулил как уебище. 4 раза на фортике голиафа заводил в огонь.",
"ПротПал. Пиздит больше чем делает. Запулил аддов без хила. Просто конченный.",
"БДК. Просто конченный уебан. в 20 кее в кчл пошел через лево, 0 контроля и ливнул в середине ключа.",
"Медведь. Лоускильное уебищец",
"Фмаг. Русский хуесос который не может отследить копии на маге. Вайпнул всех в атале.",
"ВДХ. Слабенький с 2 чд и роутами из залупы.",
"Хавок. Что=то пиздит не по делу. Просто конченная помойка.",
"Рога. Не дамажит. Ливнул с лорда и леди хотя было 6:30 могли успеть",
"ПротПал. Не живет нихуя. Пиздит что не хилят. Возможно это альт убивика",
"ВДХ. Не умеет жать сейвы. Не держит аптайм шипов, пулит пак без шипов и не юзает клеймо или fel devastation. Фрик ебаный.",
"БМ. Очень слабо отыгрывает. Бегает где-то в ебенях, в луже друида не стоит, по ебалу получает лишнего.",
"ВДХ. Умер на голиафе 2 раза + прокнул чд на 10 стаках всего. Умер на треше перед голиафом на тиранике лол.",
"Havoc. Не отдал тринкет  с фиракка. Мусор 3.3к рио. Русский чел бтв.",
"ВДХ. Чурка ливнул с кея. ",
"ВДХ. Чурка еще тот. Фишечник хуев",
"Фмаг. Не юзает масс барьеры и даже не понимает зачем их жать.",
"ШП. Не может рассчитать бурсты на щит + не сдавал пати хилку на самые важные моменты.",
"Фмаг. Бущеный хуесос. Дамага нет, понимания мобов в вечном цветении нихуя нет.",
"ВДХ. Фрик жмет мету на клив 1 босса в EB на 3% хп и затем на тираник неделе умирает от следующего запула",
"",
"",
"ВДХ. ЧСВ чел, кикнул с пати т.к. нет мелда",
"ШП. Ливнул с ключа еблан",
"Balance. Русский чурка. Ливнул с рейда после 2 вайпов. ",
"ВДХ. Хуесос ливнул",
"Рдру. Лагал как чурка. 3 раза на боссе вылетел. У круцика он в чс был.",
"ВДХ. Чурка с говнороутами. Сломали BH спулил 3 дерева перед 2 боссом. Спулил моба на мосту после 2 босса и сдох ахахаха.",
"ФМаг. Чурка инсталивнул после дисконнекта танка, хотя времени было вагон, мог и подождать реконнекта. Не умеет байтить кентавров",
"ВДХ. ЧСВ уебан. В целом норм, но чурка токсичная пиздит дохуя",
"ШП. Не дамажит. Дпс как у Fumezz мага.",
"БДК. Еблан на 3 боссе рейда кикнул второго танка за афк. Я в ахуе",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"лошок",
"Фекал. Уебан не жмет CR. Еще и на говне играет",
"ДК. Согильдеец саламыча. Конченный еблан ливнул сука тварь",
"Долбоеб на РЛе",
"Ршам. Хуйло ливнул с ключа. Типичная немецкая мразь с блэкрока",
"Ретрик. Хуйло ливнул с ключа",
"Баланс. Уебок ливнул с ключа. Немецкий уебанчик",
"Ршам. Еблан сучий ливнул с ключа",
"Ткач монк. Ебло пригласил друга танка который полный еблан имбецил даун чмо спулил 2 пака в туманах и челики поливали",
"БДК. Еблан спулил 2 пака в туманах. Тварь ебаная я рот его французский ебал.",
"Брюмонк. Ливнул с ключа",
"ФДК. Русский конченный еблан. Тактику не знает, мозгов нихуя не имеет.",
"Ршам. Еблан ливнул с ключа",
"Ршам. Ебалай ливнул",
"Ршам. Немецкий фрик, диспелит как еблан и не хилит",
"Сова. Какой-то еблан то принял в рейд, то кикнул, то снова принял, то снова кикнул. Неадекват.",
"Ршам. Русский чсв уебан.",
"ФДК. Клоун не дамажит, нихуя не видит, не может реснуть.",
"Аркан. Не жмет сейвы, не дамажит, не знает тактики на боссов. Типикал ебло на маге",
"Сова. Конченный, не дамажит, не отходит от механик. Еще и пиздит че то",
"ФДК. Умер на ласте в тризне внизу адда не убил. По овералл дпс на последнем месте ниже аркана и ассасина.",
"ФДК. Еблан не дамажит вообще + обосрался сдох на 1 паке, потом подпулил змеем своим пак и ливнул",
"Протвар. Клоун на танке, не удержал агро на паке, потом спулил 3 пака и умер ебалай.",
"АДК. Еблан играет на АДК когда ФДК мета. Пиздел на меня что я не сдал БЛ, сам умер от агро на треше. ДПС ниже танка",
"Элем. Не то чтобы совсем еблан, но еблан.",
"АссаРога. Просто еблан ноет про рестелс.",
"Ретрик. Клоун со старта ключа афк на 30с встал",
"ФДК. Клоун инста ливнул после 1 вайпа",
"Элем. Клоун инста ливнул после 1 вайпа",
"Аркан. Редкостный еблан без дпс. 800к во второй пул в тирне",
"Элем. Сдох, реснулсяс в мобах в осаде на 1 боссе, я его реснул и в момент реса он оффнулся",
"ФДК. Норм чел, но не дамажит совсем.",
"Энх. Не дамажит нихуя. Умер 4 раза подряд от кислотной лужи в тирне лол",
"ФростМаг. ЧСВ хуесос без дпс",
"АДК. Конченный еблан дамажит с пула, переагрил, встал и не может пройти к нам",
"Сова. ЧСВ мусор. Че дамажит, но не дохуя, но чсв выше некуда.",
"Ретрик. Конченный еблан. Ливнул перед стартом кея зачем то и спулил адов чтобы они нас типа убили ахахахах)",
"Элем. Типичный французский уебан. Даже не умеет анализировать детейлс.",
"Протпал. Вжал бабл+хс на ласте босса. Было не тайм, но поступок шелухи ебаной",
"Дестрик. Еблуша решил мне в 10 ключе грудак продать который ему все равно не нужен был. Пидарас мусорный",
"Элем. ЧСВ хуесос. Сказал что еще раз меня уронишь и я ливну. Тварь ебаная.",
"Элем. Не дамажит + ливнулд после первого пула. Чсв мусор",
"Энх. Не дамажит",
"Ретрик. Уебок не умеет жать сейвы. Просто кретин сейвит бабл на следующий патч",
"Саб. Играет в сабе когда мета ассасинов. Дамажит меньше баера ахахахах",
"Энх. Метадрочер, ноль дпс типичный еблан.",
"Протпал. Не живет конч.",
"ФДК. Мразь ливнул с ключа",
"Фурик. Еблан СДВГшный. Не выдержал общения в чате ливнул до ключа, помойка коричневая",
"Протпал. Уебок по середине пака ливнул ",
"Протвар. Тварь ебаная ливнул с ключа после первого пула.",
"Баланс. 1 пул не стеми таликами ниже танка. Затем менял талики 2 минуты. Умер на боссе из-за дисконеекта. дпс как у танка кекв",
"ФДК. Дпс как у танка, конченный еблан",
"Энх. Еблан не может прожать ни одной сейв абилки. Словил все что можно. Умер как уеба ",
"Протал. Чурка не умеет жаться сдох мразь на пуле",
"Протпал. Какой-то лох без PS в туманах не может осилить пак перед 1 боссом, хуесосит его как суку",
"Дестрик. Был друг - стал враг. Прошли с ним изи 15 боралус, а отом он перестал брать в ключи, паскуда тварь",
"Энх. Запулил пак, сдох и ливнул. Хотя таймера хватало.",
"",
"Энх.Слабый даун который еще че то пиздел на меня за смерти типа. еще после кея написал что ему ключ уебку лоускильному заруинили",
"",
"Протпал. Слабенький. не смог простоять первый па в грим батоле минуту",
"Протпал. Алкаш русский витязь",
"Протпал. Агрит мобов как ебло.",
"ДЦП. Не хилит и ливнул на первом паке свода",
"Протпал. не смог выдержать в 15 своде 1 пак.",
"Фрост. Еблане не может талики перед данжем сменить.",
"конченный еблан троллит",
"вдх. 2 врыва в пак 2 смерти инста",
"БДК. Роуты параши",
"ДЦП с хуевым инетом",
"Пвар. Пулит паки по 10-15 сек. Пока собирает мобы срываются",
"ВДХ. Танчит очень странно, потом еще начал что-то магу агрессивно высказывать хотя сам не прав был",
"ВДХ. Не прям чтобы тупой еблан, но чейны и маршруты дерьмо. А на биг запуле 4 паков в приорате откис и вышли с ключа",
"",
"Ршам. Слабый даун. Не может прохилить 3 босса в расселине. 3.2м хпс обоссаных",
"АМаг. Дерьмо без киков и дпс",
"Маг. Еблан конченный. Не может в свою очередь дать СС. Не может вовремя дать БЛ. Ливнул с ключа хотя это был тайм. Тупая мразь",
"Маг. Тупенький лоурио челик. Мозгов нет. Что взять с глупого необучаемого ебланчика",
"Лок. Не дамажит. Умирает по кд. Заруинил ключ",
"Хант. Еблан 2 раза сдох от магнита на ласте в мехагоне. Просто тупая мразь. Хоть че то и дпсит",
"ВДХ. Конченная агрессивная мразь которая пиздит безумолку",
"Вар. Альт уебана Шинсо(ВДХ) который гнилая мразь. Со слюнями у рта пиздит неумолкая чсвшник",
"Маг. Странный тип. Не самый конченный какого я видел, но просто умирал там где не должен был. Смешные смерти, может бущеный",
"ГвардДруид. Клоун который на адде не прожимается и потом пишет что дц ему должен щит давать. Когда у того не в кд барскин ахаахх",
"ВДХ. Не умирал. Но роут говна. Скинул один роут, по факту пулил совсем другое. Странный чел, я бы с ним еще раз не пошел",
"",
"ДЦ. Очень слабо хилит и по мане проседает, не пьет между пулами",
"ДЦ. Помойка нехилящая, постоянно нужна мана, умирает по кд. Самую важную цель баланс друида не хилит, не щитует",
"АДК. Помойка умирает по кд",
"ВДХ. Маршруты параши. Умер 3 раза на боссе ахахааха валенок",
"ВДХ. Хуевые маршруты, не умеет скипать в жиле",
"Брюмонк. Ебалай не живет. Не может круг дать. Сдох как еблан. Еще и пиздит ficus up ааахахаах",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
},
["autoUpdate"] = true,
["skipGuild"] = true,
["chatmsg"] = true,
["filterTotal"] = 6,
["dateList"] = {
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"02 Jul 2023",
"04 Jul 2023",
"05 Jul 2023",
"05 Jul 2023",
"06 Jul 2023",
"06 Jul 2023",
"08 Jul 2023",
"09 Jul 2023",
"09 Jul 2023",
"09 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"13 Jul 2023",
"15 Jul 2023",
"15 Jul 2023",
"16 Jul 2023",
"16 Jul 2023",
"16 Jul 2023",
"17 Jul 2023",
"17 Jul 2023",
"17 Jul 2023",
"18 Jul 2023",
"19 Jul 2023",
"20 Jul 2023",
"21 Jul 2023",
"22 Jul 2023",
"22 Jul 2023",
"22 Jul 2023",
"22 Jul 2023",
"23 Jul 2023",
"23 Jul 2023",
"27 Jul 2023",
"27 Jul 2023",
"28 Jul 2023",
"30 Jul 2023",
"30 Jul 2023",
"01 Aug 2023",
"01 Aug 2023",
"02 Aug 2023",
"06 Aug 2023",
"08 Aug 2023",
"09 Aug 2023",
"09 Aug 2023",
"09 Aug 2023",
"09 Aug 2023",
"09 Aug 2023",
"11 Aug 2023",
"15 Aug 2023",
"15 Aug 2023",
"23 Aug 2023",
"27 Aug 2023",
"27 Aug 2023",
"05 Sep 2023",
"09 Sep 2023",
"09 Sep 2023",
"09 Sep 2023",
"14 Sep 2023",
"14 Sep 2023",
"15 Sep 2023",
"15 Sep 2023",
"15 Sep 2023",
"19 Sep 2023",
"19 Sep 2023",
"19 Sep 2023",
"20 Sep 2023",
"21 Sep 2023",
"22 Sep 2023",
"22 Sep 2023",
"22 Sep 2023",
"24 Sep 2023",
"24 Sep 2023",
"26 Sep 2023",
"28 Sep 2023",
"01 Oct 2023",
"04 Oct 2023",
"04 Oct 2023",
"09 Oct 2023",
"11 Oct 2023",
"12 Oct 2023",
"13 Oct 2023",
"14 Oct 2023",
"14 Oct 2023",
"16 Oct 2023",
"17 Oct 2023",
"17 Oct 2023",
"18 Oct 2023",
"19 Oct 2023",
"21 Oct 2023",
"21 Oct 2023",
"06 Nov 2023",
"28 Nov 2023",
"28 Nov 2023",
"01 Dec 2023",
"03 Dec 2023",
"10 Dec 2023",
"16 Dec 2023",
"29 Dec 2023",
"29 Dec 2023",
"30 Dec 2023",
"01 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"02 Jan 2024",
"06 Jan 2024",
"06 Jan 2024",
"07 Jan 2024",
"12 Jan 2024",
"12 Jan 2024",
"13 Jan 2024",
"14 Jan 2024",
"17 Jan 2024",
"23 Jan 2024",
"26 Jan 2024",
"27 Jan 2024",
"27 Jan 2024",
"31 Jan 2024",
"02 Feb 2024",
"03 Feb 2024",
"06 Feb 2024",
"15 Feb 2024",
"16 Feb 2024",
"17 Feb 2024",
"19 Feb 2024",
"19 Feb 2024",
"20 Feb 2024",
"29 Feb 2024",
"09 Mar 2024",
"13 Mar 2024",
"16 Apr 2024",
"05 May 2024",
"08 May 2024",
"09 May 2024",
"09 May 2024",
"11 May 2024",
"12 May 2024",
"13 May 2024",
"12 Jun 2024",
"03 Jul 2024",
"27 Aug 2024",
"27 Aug 2024",
"27 Aug 2024",
"27 Aug 2024",
"02 Sep 2024",
"02 Sep 2024",
"02 Sep 2024",
"02 Sep 2024",
"02 Sep 2024",
"11 Sep 2024",
"18 Sep 2024",
"18 Sep 2024",
"18 Sep 2024",
"19 Sep 2024",
"19 Sep 2024",
"23 Sep 2024",
"24 Sep 2024",
"25 Sep 2024",
"25 Sep 2024",
"28 Sep 2024",
"01 Oct 2024",
"02 Oct 2024",
"05 Oct 2024",
"05 Oct 2024",
"10 Oct 2024",
"11 Oct 2024",
"11 Oct 2024",
"11 Oct 2024",
"13 Oct 2024",
"20 Oct 2024",
"20 Oct 2024",
"21 Oct 2024",
"21 Oct 2024",
"23 Oct 2024",
"23 Oct 2024",
"23 Oct 2024",
"23 Oct 2024",
"23 Oct 2024",
"23 Oct 2024",
"30 Oct 2024",
"02 Nov 2024",
"02 Nov 2024",
"03 Nov 2024",
"03 Nov 2024",
"04 Nov 2024",
"04 Nov 2024",
"04 Nov 2024",
"06 Nov 2024",
"07 Nov 2024",
"10 Nov 2024",
"14 Nov 2024",
"14 Nov 2024",
"14 Nov 2024",
"15 Nov 2024",
"17 Nov 2024",
"17 Nov 2024",
"19 Nov 2024",
"19 Nov 2024",
"21 Nov 2024",
"22 Nov 2024",
"27 Nov 2024",
"27 Nov 2024",
"27 Nov 2024",
"30 Nov 2024",
"30 Nov 2024",
"01 Dec 2024",
"03 Dec 2024",
"11 Dec 2024",
"24 Dec 2024",
"29 Dec 2024",
"30 Dec 2024",
"02 Jan 2025",
"04 Jan 2025",
"04 Jan 2025",
"04 Jan 2025",
"04 Jan 2025",
"29 May 2025",
"30 May 2025",
"12 Jun 2025",
"17 Jun 2025",
"19 Jun 2025",
"20 Jun 2025",
"20 Jun 2025",
"22 Jun 2025",
"23 Jun 2025",
"24 Jun 2025",
"25 Jun 2025",
"26 Jun 2025",
"26 Jun 2025",
"26 Jun 2025",
"26 Jun 2025",
"26 Jun 2025",
"26 Jun 2025",
"29 Jun 2025",
"30 Jun 2025",
"02 Jul 2025",
"02 Jul 2025",
"02 Jul 2025",
"03 Jul 2025",
"05 Jul 2025",
"06 Jul 2025",
"22 Jul 2025",
"26 Jul 2025",
"26 Jul 2025",
"27 Jul 2025",
"27 Jul 2025",
"28 Jul 2025",
"01 Aug 2025",
"03 Aug 2025",
"03 Aug 2025",
"03 Aug 2025",
"03 Aug 2025",
},
["filterActive"] = {
true,
true,
false,
false,
false,
false,
false,
false,
false,
false,
},
["filterList"] = {
"([word=anal] or [contains=analan]) and ([link] or [words=2])",
"[item=19019]",
"([contains=WTS] or [word=selling]) and ([contains=m+] or [contains=boost] or [contains=carry] or [contains=mythic] or [contains=gold\\ only])",
"([contains=LFW] or [word=trade] or [contains=order] or [contains=tip] or [contains=%] or [contains=max] or [word=free] or [contains=craft] or [word=mats] or [contains=pay]) and ([trade] or [item])",
"([contains=wts] or [contains=service] or [contains=sell] or [word=fast] or [contains=afk]) and (([contains=power] or [contains=pwr]) and ([contains=level] or [contains=lvl]))",
"(([guild] or ([contains=<] and [contains=>]) or ([contains=\\[] and [contains=\\]]) or ([contains=\\(] and [contains=\\)])) and ([contains=recruit] or [contains=progress] or [contains=raid] or [contains=guild] or [contains=seek] or [contains=mythic])) or ([contains=guild] and [contains=recruit])",
"[community]",
"[contains=WTS] or [contains=WTB]",
"[nonlatin]",
"[contains=trump] or [contains=communist] or [contains=communism] or [word=president] or [contains=biden] or [word=hillary] or [word=hilary] or [contains=democrat] or [contains=republican] or [contains=liberals] or [word=maga] or [word=libs] or [contains=conservatives] or [contains=libtard] or [word=pelosi] or [word=epstein] or [word=AOC] or [word=putin] or [contains=right\\ wing] or [word=dems] or [word=socialism]",
},
["filterID"] = {
"GIL0001",
"GIL0002",
"GIL0003",
"GIL0013",
"GIL0014",
"GIL0008",
"GIL0009",
"GIL0010",
"GIL0011",
"GIL0012",
},
["skipParty"] = false,
["showWarning"] = true,
["useUnitHacks"] = true,
["useLFGHacks"] = true,
["samefaction"] = true,
["asknote"] = true,
}
