
WarpDepleteDB = {
["profileKeys"] = {
["Бимладен - Ревущий фьорд"] = "All classes",
["Вантачмэн - Ревущий фьорд"] = "Default",
},
["profiles"] = {
["Default"] = {
["frameX"] = 17.33346176147461,
["frameY"] = 196.5714111328125,
},
["All classes"] = {
["keyFontSize"] = 18,
["bar2Font"] = "ITCAvantGardeGothicDemi",
["timerSuccessColor"] = "ffde8000",
["bar2FontSize"] = 14,
["deathsFontSize"] = 14,
["bar1TextureColor"] = "ffdd7f00",
["forcesTexture"] = "Melli",
["barPadding"] = 3,
["forcesFormat"] = ":custom:",
["showForcesGlow"] = false,
["verticalOffset"] = 0,
["frameX"] = 17.33346176147461,
["completedObjectivesColor"] = "ffffffff",
["currentPullFormat"] = ":custom:",
["keyDetailsFontSize"] = 13,
["timerFont"] = "ITCAvantGardeGothicDemi",
["bar3Font"] = "ITCAvantGardeGothicDemi",
["bar1Texture"] = "Melli",
["bar3TextureColor"] = "ffdc7e00",
["objectivesFont"] = "ITCAvantGardeGothicDemi",
["bar2TextureColor"] = "ffdd7f00",
["bar2Texture"] = "Melli",
["keyDetailsFont"] = "ITCAvantGardeGothicDemi",
["alignBossClear"] = "end",
["deathsFont"] = "ITCAvantGardeGothicDemi",
["forcesOverlayTexture"] = "Melli",
["bar1FontSize"] = 14,
["objectivesFontSize"] = 14,
["barHeight"] = 8,
["frameY"] = 208.7618255615234,
["bar3Texture"] = "Melli",
["timerFontSize"] = 28,
["bar1Font"] = "ITCAvantGardeGothicDemi",
["forcesOverlayTextureColor"] = "ffffffff",
["tooltipCountFormat"] = "+:percent:",
["deathsColor"] = "ffffffff",
["keyDetailsColor"] = "ff0070b2",
["forcesTextureColor"] = "ff0094eb",
["forcesFont"] = "ITCAvantGardeGothicDemi",
["objectivesOffset"] = 0,
["forcesFontSize"] = 13,
["customCurrentPullFormat"] = "+:percent: || :percentafterpull: ||",
["barWidth"] = 280,
["bar3FontSize"] = 14,
["keyFont"] = "ITCAvantGardeGothicDemi",
},
},
}
