WarpDepleteDB = {
    ["profileKeys"] = {
        ["Бимладен - Ревущий фьорд"] = "All classes",
    },
    ["profiles"] = {
        ["Default"] = {
            ["frameY"] = 196.5714111328125,
            ["frameX"] = 17.33346176147461,
        },
        ["All classes"] = {
            ["keyFontSize"] = 18,
            ["barHeight"] = 8,
            ["timerSuccessColor"] = "ffde8000",
            ["timerFontSize"] = 28,
            ["tooltipCountFormat"] = "+:percent:",
            ["deathsColor"] = "ffffffff",
            ["barPadding"] = 3,
            ["forcesFormat"] = ":custom:",
            ["showForcesGlow"] = false,
            ["verticalOffset"] = 0,
            ["frameX"] = 17.33346176147461,
            ["completedObjectivesColor"] = "ffffffff",
            ["currentPullFormat"] = ":custom:",
            ["keyDetailsFontSize"] = 13,
            ["timerFont"] = "ITCAvantGardeGothicDemi",
            ["bar3Font"] = "ITCAvantGardeGothicDemi",
            ["keyDetailsColor"] = "ff0070b2",
            ["bar3TextureColor"] = "ffdc7e00",
            ["objectivesFont"] = "ITCAvantGardeGothicDemi",
            ["bar3FontSize"] = 14,
            ["bar2Texture"] = "Melli",
            ["keyDetailsFont"] = "ITCAvantGardeGothicDemi",
            ["barWidth"] = 280,
            ["deathsFont"] = "ITCAvantGardeGothicDemi",
            ["frameY"] = 196.5714111328125,
            ["alignBossClear"] = "end",
            ["bar1FontSize"] = 14,
            ["objectivesFontSize"] = 14,
            ["bar2Font"] = "ITCAvantGardeGothicDemi",
            ["bar2TextureColor"] = "ffdd7f00",
            ["bar3Texture"] = "Melli",
            ["bar2FontSize"] = 14,
            ["bar1Font"] = "ITCAvantGardeGothicDemi",
            ["forcesOverlayTextureColor"] = "ffffffff",
            ["deathsFontSize"] = 14,
            ["bar1TextureColor"] = "ffdd7f00",
            ["forcesTexture"] = "Melli",
            ["forcesTextureColor"] = "ff0094eb",
            ["bar1Texture"] = "Melli",
            ["forcesFont"] = "ITCAvantGardeGothicDemi",
            ["forcesFontSize"] = 13,
            ["customCurrentPullFormat"] = "+:percent: || :percentafterpull: ||",
            ["objectivesOffset"] = 0,
            ["forcesOverlayTexture"] = "Melli",
            ["keyFont"] = "ITCAvantGardeGothicDemi",
        },
    },
}
